schema_version: 1
upstreams:
- https://1.1.1.1/dns-query
- https://1.0.0.1/dns-query
filters:
- url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
  name: AdGuard DNS filter
  enabled: true
  id: null
- url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
  name: AdAway Default Blocklist
  enabled: false
  id: null
- url: https://raw.githubusercontent.com/WSF-Team/WSF/refs/heads/main/documents/dns/domains/Denylist-U.txt
  name: revoke/update
  enabled: true
  id: null
- url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_36.txt
  name: 'LIT: EasyList Lithuania'
  enabled: true
  id: null
- url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_59.txt
  name: AdGuard DNS Popup Hosts filter
  enabled: true
  id: null
- url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt
  name: 1Hosts (Lite)
  enabled: true
  id: null
whitelist_filters: []
user_rules:
- tiktokv.eu
- tiktokv.com
- log16-normal-useastred.tiktokv.eu
- tnc-boot.tiktokv.com

