[DEFAULT]
banaction = iptables-multiport
banaction_allports = iptables-allports
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 1w

[sshd]
enabled = true
backend = systemd
mode = normal
port = ssh
action = iptables-multiport[name=sshd, port=ssh, protocol=tcp, chain=INPUT]
maxretry = 4
findtime = 10m
bantime = 6h
