// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit 31fd1c8c3346dfec38dfcc2e89c2ecf457cf26ff).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod ticketremote_ack_stream_command_reducer;
pub mod ticketremote_append_dev_perf_metric_reducer;
pub mod ticketremote_append_safe_operational_log_reducer;
pub mod ticketremote_append_stream_command_reducer;
pub mod ticketremote_audit_counter_type;
pub mod ticketremote_audit_event_type;
pub mod ticketremote_audit_reducer;
pub mod ticketremote_auth_config_type;
pub mod ticketremote_claim_control_reducer;
pub mod ticketremote_cleanup_expired_reducer;
pub mod ticketremote_cleanup_schedule_type;
pub mod ticketremote_control_code_owner_type;
pub mod ticketremote_control_code_request_table;
pub mod ticketremote_control_code_request_type;
pub mod ticketremote_control_session_type;
pub mod ticketremote_dev_perf_metric_type;
pub mod ticketremote_dev_perf_metrics_config_type;
pub mod ticketremote_disconnect_presence_reducer;
pub mod ticketremote_extend_control_reducer;
pub mod ticketremote_heartbeat_presence_reducer;
pub mod ticketremote_member_append_dev_perf_metric_reducer;
pub mod ticketremote_member_append_safe_operational_log_reducer;
pub mod ticketremote_member_claim_control_reducer;
pub mod ticketremote_member_close_control_code_reducer;
pub mod ticketremote_member_confirm_control_code_browser_capture_reducer;
pub mod ticketremote_member_extend_control_reducer;
pub mod ticketremote_member_prepare_control_code_reducer;
pub mod ticketremote_member_recover_stream_reducer;
pub mod ticketremote_member_release_control_reducer;
pub mod ticketremote_member_remove_member_reducer;
pub mod ticketremote_member_request_control_code_reducer;
pub mod ticketremote_member_request_keyframe_reducer;
pub mod ticketremote_member_revoke_control_reducer;
pub mod ticketremote_member_set_stream_focus_reducer;
pub mod ticketremote_member_upsert_member_reducer;
pub mod ticketremote_phone_backend_type;
pub mod ticketremote_phone_current_report_table;
pub mod ticketremote_phone_current_report_type;
pub mod ticketremote_phone_status_history_type;
pub mod ticketremote_phone_status_table;
pub mod ticketremote_phone_status_type;
pub mod ticketremote_purge_expired_stream_commands_reducer;
pub mod ticketremote_register_service_identity_reducer;
pub mod ticketremote_relay_current_report_table;
pub mod ticketremote_relay_current_report_type;
pub mod ticketremote_release_control_reducer;
pub mod ticketremote_remove_member_reducer;
pub mod ticketremote_revoke_control_reducer;
pub mod ticketremote_safe_operational_log_type;
pub mod ticketremote_service_bootstrap_reducer;
pub mod ticketremote_service_control_session_table;
pub mod ticketremote_service_control_type;
pub mod ticketremote_service_identity_type;
pub mod ticketremote_service_member_type;
pub mod ticketremote_service_phone_backend_table;
pub mod ticketremote_service_phone_type;
pub mod ticketremote_service_safe_operational_log_table;
pub mod ticketremote_service_safe_operational_log_type;
pub mod ticketremote_service_stream_command_table;
pub mod ticketremote_service_stream_command_type;
pub mod ticketremote_service_ticket_member_table;
pub mod ticketremote_service_ticket_table;
pub mod ticketremote_service_ticket_type;
pub mod ticketremote_service_viewer_presence_table;
pub mod ticketremote_service_viewer_type;
pub mod ticketremote_set_dev_perf_metrics_reducer;
pub mod ticketremote_set_stream_desired_state_reducer;
pub mod ticketremote_snapshot_runtime_tables_to_logs_reducer;
pub mod ticketremote_stream_command_signal_table;
pub mod ticketremote_stream_command_signal_type;
pub mod ticketremote_stream_command_type;
pub mod ticketremote_stream_desired_state_table;
pub mod ticketremote_stream_desired_state_type;
pub mod ticketremote_ticket_member_type;
pub mod ticketremote_ticket_summary_table;
pub mod ticketremote_ticket_summary_type;
pub mod ticketremote_ticket_type;
pub mod ticketremote_update_control_code_request_reducer;
pub mod ticketremote_update_phone_current_report_reducer;
pub mod ticketremote_update_phone_reducer;
pub mod ticketremote_update_phone_status_reducer;
pub mod ticketremote_update_relay_current_report_reducer;
pub mod ticketremote_upsert_member_reducer;
pub mod ticketremote_viewer_presence_type;
pub mod ticketremote_viewer_public_table;
pub mod ticketremote_viewer_public_type;

pub use ticketremote_ack_stream_command_reducer::ticketremote_ack_stream_command;
pub use ticketremote_append_dev_perf_metric_reducer::ticketremote_append_dev_perf_metric;
pub use ticketremote_append_safe_operational_log_reducer::ticketremote_append_safe_operational_log;
pub use ticketremote_append_stream_command_reducer::ticketremote_append_stream_command;
pub use ticketremote_audit_counter_type::TicketremoteAuditCounter;
pub use ticketremote_audit_event_type::TicketremoteAuditEvent;
pub use ticketremote_audit_reducer::ticketremote_audit;
pub use ticketremote_auth_config_type::TicketremoteAuthConfig;
pub use ticketremote_claim_control_reducer::ticketremote_claim_control;
pub use ticketremote_cleanup_expired_reducer::ticketremote_cleanup_expired;
pub use ticketremote_cleanup_schedule_type::TicketremoteCleanupSchedule;
pub use ticketremote_control_code_owner_type::TicketremoteControlCodeOwner;
pub use ticketremote_control_code_request_table::*;
pub use ticketremote_control_code_request_type::TicketremoteControlCodeRequest;
pub use ticketremote_control_session_type::TicketremoteControlSession;
pub use ticketremote_dev_perf_metric_type::TicketremoteDevPerfMetric;
pub use ticketremote_dev_perf_metrics_config_type::TicketremoteDevPerfMetricsConfig;
pub use ticketremote_disconnect_presence_reducer::ticketremote_disconnect_presence;
pub use ticketremote_extend_control_reducer::ticketremote_extend_control;
pub use ticketremote_heartbeat_presence_reducer::ticketremote_heartbeat_presence;
pub use ticketremote_member_append_dev_perf_metric_reducer::ticketremote_member_append_dev_perf_metric;
pub use ticketremote_member_append_safe_operational_log_reducer::ticketremote_member_append_safe_operational_log;
pub use ticketremote_member_claim_control_reducer::ticketremote_member_claim_control;
pub use ticketremote_member_close_control_code_reducer::ticketremote_member_close_control_code;
pub use ticketremote_member_confirm_control_code_browser_capture_reducer::ticketremote_member_confirm_control_code_browser_capture;
pub use ticketremote_member_extend_control_reducer::ticketremote_member_extend_control;
pub use ticketremote_member_prepare_control_code_reducer::ticketremote_member_prepare_control_code;
pub use ticketremote_member_recover_stream_reducer::ticketremote_member_recover_stream;
pub use ticketremote_member_release_control_reducer::ticketremote_member_release_control;
pub use ticketremote_member_remove_member_reducer::ticketremote_member_remove_member;
pub use ticketremote_member_request_control_code_reducer::ticketremote_member_request_control_code;
pub use ticketremote_member_request_keyframe_reducer::ticketremote_member_request_keyframe;
pub use ticketremote_member_revoke_control_reducer::ticketremote_member_revoke_control;
pub use ticketremote_member_set_stream_focus_reducer::ticketremote_member_set_stream_focus;
pub use ticketremote_member_upsert_member_reducer::ticketremote_member_upsert_member;
pub use ticketremote_phone_backend_type::TicketremotePhoneBackend;
pub use ticketremote_phone_current_report_table::*;
pub use ticketremote_phone_current_report_type::TicketremotePhoneCurrentReport;
pub use ticketremote_phone_status_history_type::TicketremotePhoneStatusHistory;
pub use ticketremote_phone_status_table::*;
pub use ticketremote_phone_status_type::TicketremotePhoneStatus;
pub use ticketremote_purge_expired_stream_commands_reducer::ticketremote_purge_expired_stream_commands;
pub use ticketremote_register_service_identity_reducer::ticketremote_register_service_identity;
pub use ticketremote_relay_current_report_table::*;
pub use ticketremote_relay_current_report_type::TicketremoteRelayCurrentReport;
pub use ticketremote_release_control_reducer::ticketremote_release_control;
pub use ticketremote_remove_member_reducer::ticketremote_remove_member;
pub use ticketremote_revoke_control_reducer::ticketremote_revoke_control;
pub use ticketremote_safe_operational_log_type::TicketremoteSafeOperationalLog;
pub use ticketremote_service_bootstrap_reducer::ticketremote_service_bootstrap;
pub use ticketremote_service_control_session_table::*;
pub use ticketremote_service_control_type::TicketremoteServiceControl;
pub use ticketremote_service_identity_type::TicketremoteServiceIdentity;
pub use ticketremote_service_member_type::TicketremoteServiceMember;
pub use ticketremote_service_phone_backend_table::*;
pub use ticketremote_service_phone_type::TicketremoteServicePhone;
pub use ticketremote_service_safe_operational_log_table::*;
pub use ticketremote_service_safe_operational_log_type::TicketremoteServiceSafeOperationalLog;
pub use ticketremote_service_stream_command_table::*;
pub use ticketremote_service_stream_command_type::TicketremoteServiceStreamCommand;
pub use ticketremote_service_ticket_member_table::*;
pub use ticketremote_service_ticket_table::*;
pub use ticketremote_service_ticket_type::TicketremoteServiceTicket;
pub use ticketremote_service_viewer_presence_table::*;
pub use ticketremote_service_viewer_type::TicketremoteServiceViewer;
pub use ticketremote_set_dev_perf_metrics_reducer::ticketremote_set_dev_perf_metrics;
pub use ticketremote_set_stream_desired_state_reducer::ticketremote_set_stream_desired_state;
pub use ticketremote_snapshot_runtime_tables_to_logs_reducer::ticketremote_snapshot_runtime_tables_to_logs;
pub use ticketremote_stream_command_signal_table::*;
pub use ticketremote_stream_command_signal_type::TicketremoteStreamCommandSignal;
pub use ticketremote_stream_command_type::TicketremoteStreamCommand;
pub use ticketremote_stream_desired_state_table::*;
pub use ticketremote_stream_desired_state_type::TicketremoteStreamDesiredState;
pub use ticketremote_ticket_member_type::TicketremoteTicketMember;
pub use ticketremote_ticket_summary_table::*;
pub use ticketremote_ticket_summary_type::TicketremoteTicketSummary;
pub use ticketremote_ticket_type::TicketremoteTicket;
pub use ticketremote_update_control_code_request_reducer::ticketremote_update_control_code_request;
pub use ticketremote_update_phone_current_report_reducer::ticketremote_update_phone_current_report;
pub use ticketremote_update_phone_reducer::ticketremote_update_phone;
pub use ticketremote_update_phone_status_reducer::ticketremote_update_phone_status;
pub use ticketremote_update_relay_current_report_reducer::ticketremote_update_relay_current_report;
pub use ticketremote_upsert_member_reducer::ticketremote_upsert_member;
pub use ticketremote_viewer_presence_type::TicketremoteViewerPresence;
pub use ticketremote_viewer_public_table::*;
pub use ticketremote_viewer_public_type::TicketremoteViewerPublic;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    TicketremoteAckStreamCommand {
        command_id: String,
        status: String,
        reason: String,
        now_arg: String,
    },
    TicketremoteAppendDevPerfMetric {
        ticket_id: String,
        source: String,
        metric_name: String,
        phase: String,
        flow_id: String,
        value_millis: u32,
        ok: bool,
        detail_json: String,
        now_arg: String,
    },
    TicketremoteAppendSafeOperationalLog {
        ticket_id: String,
        source: String,
        level: String,
        event: String,
        correlation_id: String,
        detail_json: String,
        now_arg: String,
    },
    TicketremoteAppendStreamCommand {
        ticket_id: String,
        backend_id: String,
        command_id: String,
        command_type: String,
        revision: String,
        reason: String,
        payload_json: String,
        ttl_millis: u32,
        now_arg: String,
    },
    TicketremoteAudit {
        ticket_id: String,
        actor_email: String,
        event: String,
        payload_json: String,
        now_arg: String,
    },
    TicketremoteClaimControl {
        ticket_id: String,
        session_id: String,
        email: String,
        now_arg: String,
    },
    TicketremoteCleanupExpired {
        ticket_id: String,
        now_arg: String,
        batch_size: u32,
    },
    TicketremoteDisconnectPresence {
        ticket_id: String,
        session_id: String,
        now_arg: String,
    },
    TicketremoteExtendControl {
        ticket_id: String,
        session_id: String,
        email: String,
        now_arg: String,
    },
    TicketremoteHeartbeatPresence {
        ticket_id: String,
        session_id: String,
        email: String,
        display_name: String,
        page: String,
        connected: bool,
        now_arg: String,
    },
    TicketremoteMemberAppendDevPerfMetric {
        ticket_id: String,
        metric_name: String,
        phase: String,
        flow_id: String,
        value_millis: u32,
        ok: bool,
        detail_json: String,
    },
    TicketremoteMemberAppendSafeOperationalLog {
        ticket_id: String,
        level: String,
        event: String,
        correlation_id: String,
        detail_json: String,
    },
    TicketremoteMemberClaimControl {
        ticket_id: String,
    },
    TicketremoteMemberCloseControlCode {
        ticket_id: String,
        backend_id: String,
        session_id: String,
        request_id: String,
        reason: String,
    },
    TicketremoteMemberConfirmControlCodeBrowserCapture {
        ticket_id: String,
        backend_id: String,
        session_id: String,
        request_id: String,
        candidate_frame_epoch: String,
        candidate_frame_sequence: String,
        accepted_reason: String,
    },
    TicketremoteMemberExtendControl {
        ticket_id: String,
    },
    TicketremoteMemberPrepareControlCode {
        ticket_id: String,
        backend_id: String,
        reason: String,
    },
    TicketremoteMemberRecoverStream {
        ticket_id: String,
        backend_id: String,
        reason: String,
    },
    TicketremoteMemberReleaseControl {
        ticket_id: String,
        reason: String,
    },
    TicketremoteMemberRemoveMember {
        ticket_id: String,
        email: String,
    },
    TicketremoteMemberRequestControlCode {
        ticket_id: String,
        backend_id: String,
        session_id: String,
        digits: String,
    },
    TicketremoteMemberRequestKeyframe {
        ticket_id: String,
        backend_id: String,
        reason: String,
    },
    TicketremoteMemberRevokeControl {
        ticket_id: String,
        reason: String,
    },
    TicketremoteMemberSetStreamFocus {
        ticket_id: String,
        backend_id: String,
        session_id: String,
        active: bool,
        reason: String,
    },
    TicketremoteMemberUpsertMember {
        ticket_id: String,
        email: String,
        role: String,
    },
    TicketremotePurgeExpiredStreamCommands {
        ticket_id: String,
        now_arg: String,
        batch_size: u32,
    },
    TicketremoteRegisterServiceIdentity {
        ticket_id: String,
        now: String,
    },
    TicketremoteReleaseControl {
        ticket_id: String,
        session_id: String,
        email: String,
        reason: String,
        now_arg: String,
    },
    TicketremoteRemoveMember {
        ticket_id: String,
        actor_email: String,
        email: String,
        now_arg: String,
    },
    TicketremoteRevokeControl {
        ticket_id: String,
        actor_email: String,
        reason: String,
        now_arg: String,
    },
    TicketremoteServiceBootstrap {
        ticket_id: String,
        display_name: String,
        admin_email: String,
        phone_backend_id: String,
        phone_base_url: String,
        phone_attach_name: String,
        auth_issuer: String,
        auth_audience: String,
    },
    TicketremoteSetDevPerfMetrics {
        ticket_id: String,
        enabled: bool,
        reason: String,
        expires_at: String,
        now_arg: String,
    },
    TicketremoteSetStreamDesiredState {
        ticket_id: String,
        backend_id: String,
        desired_active: bool,
        viewer_count: u32,
        reason: String,
        revision: String,
        updated_by: String,
        now_arg: String,
    },
    TicketremoteSnapshotRuntimeTablesToLogs {
        ticket_id: String,
        now_arg: String,
        batch_size: u32,
    },
    TicketremoteUpdateControlCodeRequest {
        ticket_id: String,
        request_id: String,
        status: String,
        reason: String,
        message: String,
        stream_epoch: String,
        frame_sequence: String,
        min_frame_sequence: String,
        result_frame_epoch: String,
        result_min_frame_sequence: String,
        result_proof: String,
        result_proof_at: String,
        cleanup_pending: bool,
        now_arg: String,
    },
    TicketremoteUpdatePhone {
        ticket_id: String,
        backend_id: String,
        attach_name: String,
        base_url: String,
        desired_state: String,
        health_json: String,
        last_error: String,
        now_arg: String,
    },
    TicketremoteUpdatePhoneCurrentReport {
        ticket_id: String,
        backend_id: String,
        stream_state: String,
        desired_active: bool,
        last_command_id: String,
        last_command_revision: String,
        status_json: String,
        now_arg: String,
    },
    TicketremoteUpdatePhoneStatus {
        ticket_id: String,
        backend_id: String,
        attach_name: String,
        base_url: String,
        desired_state: String,
        health_json: String,
        last_error: String,
        now_arg: String,
    },
    TicketremoteUpdateRelayCurrentReport {
        ticket_id: String,
        backend_id: String,
        video_clients: u32,
        stream_verdict: String,
        last_frame_ago_millis: u32,
        frames_forwarded: String,
        status_json: String,
        now_arg: String,
    },
    TicketremoteUpsertMember {
        ticket_id: String,
        actor_email: String,
        email: String,
        role: String,
        now_arg: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::TicketremoteAckStreamCommand { .. } => "ticketremote_ack_stream_command",
            Reducer::TicketremoteAppendDevPerfMetric { .. } => {
                "ticketremote_append_dev_perf_metric"
            }
            Reducer::TicketremoteAppendSafeOperationalLog { .. } => {
                "ticketremote_append_safe_operational_log"
            }
            Reducer::TicketremoteAppendStreamCommand { .. } => "ticketremote_append_stream_command",
            Reducer::TicketremoteAudit { .. } => "ticketremote_audit",
            Reducer::TicketremoteClaimControl { .. } => "ticketremote_claim_control",
            Reducer::TicketremoteCleanupExpired { .. } => "ticketremote_cleanup_expired",
            Reducer::TicketremoteDisconnectPresence { .. } => "ticketremote_disconnect_presence",
            Reducer::TicketremoteExtendControl { .. } => "ticketremote_extend_control",
            Reducer::TicketremoteHeartbeatPresence { .. } => "ticketremote_heartbeat_presence",
            Reducer::TicketremoteMemberAppendDevPerfMetric { .. } => {
                "ticketremote_member_append_dev_perf_metric"
            }
            Reducer::TicketremoteMemberAppendSafeOperationalLog { .. } => {
                "ticketremote_member_append_safe_operational_log"
            }
            Reducer::TicketremoteMemberClaimControl { .. } => "ticketremote_member_claim_control",
            Reducer::TicketremoteMemberCloseControlCode { .. } => {
                "ticketremote_member_close_control_code"
            }
            Reducer::TicketremoteMemberConfirmControlCodeBrowserCapture { .. } => {
                "ticketremote_member_confirm_control_code_browser_capture"
            }
            Reducer::TicketremoteMemberExtendControl { .. } => "ticketremote_member_extend_control",
            Reducer::TicketremoteMemberPrepareControlCode { .. } => {
                "ticketremote_member_prepare_control_code"
            }
            Reducer::TicketremoteMemberRecoverStream { .. } => "ticketremote_member_recover_stream",
            Reducer::TicketremoteMemberReleaseControl { .. } => {
                "ticketremote_member_release_control"
            }
            Reducer::TicketremoteMemberRemoveMember { .. } => "ticketremote_member_remove_member",
            Reducer::TicketremoteMemberRequestControlCode { .. } => {
                "ticketremote_member_request_control_code"
            }
            Reducer::TicketremoteMemberRequestKeyframe { .. } => {
                "ticketremote_member_request_keyframe"
            }
            Reducer::TicketremoteMemberRevokeControl { .. } => "ticketremote_member_revoke_control",
            Reducer::TicketremoteMemberSetStreamFocus { .. } => {
                "ticketremote_member_set_stream_focus"
            }
            Reducer::TicketremoteMemberUpsertMember { .. } => "ticketremote_member_upsert_member",
            Reducer::TicketremotePurgeExpiredStreamCommands { .. } => {
                "ticketremote_purge_expired_stream_commands"
            }
            Reducer::TicketremoteRegisterServiceIdentity { .. } => {
                "ticketremote_register_service_identity"
            }
            Reducer::TicketremoteReleaseControl { .. } => "ticketremote_release_control",
            Reducer::TicketremoteRemoveMember { .. } => "ticketremote_remove_member",
            Reducer::TicketremoteRevokeControl { .. } => "ticketremote_revoke_control",
            Reducer::TicketremoteServiceBootstrap { .. } => "ticketremote_service_bootstrap",
            Reducer::TicketremoteSetDevPerfMetrics { .. } => "ticketremote_set_dev_perf_metrics",
            Reducer::TicketremoteSetStreamDesiredState { .. } => {
                "ticketremote_set_stream_desired_state"
            }
            Reducer::TicketremoteSnapshotRuntimeTablesToLogs { .. } => {
                "ticketremote_snapshot_runtime_tables_to_logs"
            }
            Reducer::TicketremoteUpdateControlCodeRequest { .. } => {
                "ticketremote_update_control_code_request"
            }
            Reducer::TicketremoteUpdatePhone { .. } => "ticketremote_update_phone",
            Reducer::TicketremoteUpdatePhoneCurrentReport { .. } => {
                "ticketremote_update_phone_current_report"
            }
            Reducer::TicketremoteUpdatePhoneStatus { .. } => "ticketremote_update_phone_status",
            Reducer::TicketremoteUpdateRelayCurrentReport { .. } => {
                "ticketremote_update_relay_current_report"
            }
            Reducer::TicketremoteUpsertMember { .. } => "ticketremote_upsert_member",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
                        Reducer::TicketremoteAckStreamCommand{
                command_id,
                status,
                reason,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_ack_stream_command_reducer::TicketremoteAckStreamCommandArgs {
                command_id: command_id.clone(),
                status: status.clone(),
                reason: reason.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteAppendDevPerfMetric{
                ticket_id,
                source,
                metric_name,
                phase,
                flow_id,
                value_millis,
                ok,
                detail_json,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_append_dev_perf_metric_reducer::TicketremoteAppendDevPerfMetricArgs {
                ticket_id: ticket_id.clone(),
                source: source.clone(),
                metric_name: metric_name.clone(),
                phase: phase.clone(),
                flow_id: flow_id.clone(),
                value_millis: value_millis.clone(),
                ok: ok.clone(),
                detail_json: detail_json.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteAppendSafeOperationalLog{
                ticket_id,
                source,
                level,
                event,
                correlation_id,
                detail_json,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_append_safe_operational_log_reducer::TicketremoteAppendSafeOperationalLogArgs {
                ticket_id: ticket_id.clone(),
                source: source.clone(),
                level: level.clone(),
                event: event.clone(),
                correlation_id: correlation_id.clone(),
                detail_json: detail_json.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteAppendStreamCommand{
                ticket_id,
                backend_id,
                command_id,
                command_type,
                revision,
                reason,
                payload_json,
                ttl_millis,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_append_stream_command_reducer::TicketremoteAppendStreamCommandArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                command_id: command_id.clone(),
                command_type: command_type.clone(),
                revision: revision.clone(),
                reason: reason.clone(),
                payload_json: payload_json.clone(),
                ttl_millis: ttl_millis.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteAudit{
                ticket_id,
                actor_email,
                event,
                payload_json,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_audit_reducer::TicketremoteAuditArgs {
                ticket_id: ticket_id.clone(),
                actor_email: actor_email.clone(),
                event: event.clone(),
                payload_json: payload_json.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteClaimControl{
                ticket_id,
                session_id,
                email,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_claim_control_reducer::TicketremoteClaimControlArgs {
                ticket_id: ticket_id.clone(),
                session_id: session_id.clone(),
                email: email.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteCleanupExpired{
                ticket_id,
                now_arg,
                batch_size,
}             => __sats::bsatn::to_vec(&ticketremote_cleanup_expired_reducer::TicketremoteCleanupExpiredArgs {
                ticket_id: ticket_id.clone(),
                now_arg: now_arg.clone(),
                batch_size: batch_size.clone(),
}),
            Reducer::TicketremoteDisconnectPresence{
                ticket_id,
                session_id,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_disconnect_presence_reducer::TicketremoteDisconnectPresenceArgs {
                ticket_id: ticket_id.clone(),
                session_id: session_id.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteExtendControl{
                ticket_id,
                session_id,
                email,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_extend_control_reducer::TicketremoteExtendControlArgs {
                ticket_id: ticket_id.clone(),
                session_id: session_id.clone(),
                email: email.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteHeartbeatPresence{
                ticket_id,
                session_id,
                email,
                display_name,
                page,
                connected,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_heartbeat_presence_reducer::TicketremoteHeartbeatPresenceArgs {
                ticket_id: ticket_id.clone(),
                session_id: session_id.clone(),
                email: email.clone(),
                display_name: display_name.clone(),
                page: page.clone(),
                connected: connected.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteMemberAppendDevPerfMetric{
                ticket_id,
                metric_name,
                phase,
                flow_id,
                value_millis,
                ok,
                detail_json,
}             => __sats::bsatn::to_vec(&ticketremote_member_append_dev_perf_metric_reducer::TicketremoteMemberAppendDevPerfMetricArgs {
                ticket_id: ticket_id.clone(),
                metric_name: metric_name.clone(),
                phase: phase.clone(),
                flow_id: flow_id.clone(),
                value_millis: value_millis.clone(),
                ok: ok.clone(),
                detail_json: detail_json.clone(),
}),
            Reducer::TicketremoteMemberAppendSafeOperationalLog{
                ticket_id,
                level,
                event,
                correlation_id,
                detail_json,
}             => __sats::bsatn::to_vec(&ticketremote_member_append_safe_operational_log_reducer::TicketremoteMemberAppendSafeOperationalLogArgs {
                ticket_id: ticket_id.clone(),
                level: level.clone(),
                event: event.clone(),
                correlation_id: correlation_id.clone(),
                detail_json: detail_json.clone(),
}),
            Reducer::TicketremoteMemberClaimControl{
                ticket_id,
}             => __sats::bsatn::to_vec(&ticketremote_member_claim_control_reducer::TicketremoteMemberClaimControlArgs {
                ticket_id: ticket_id.clone(),
}),
            Reducer::TicketremoteMemberCloseControlCode{
                ticket_id,
                backend_id,
                session_id,
                request_id,
                reason,
}             => __sats::bsatn::to_vec(&ticketremote_member_close_control_code_reducer::TicketremoteMemberCloseControlCodeArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                session_id: session_id.clone(),
                request_id: request_id.clone(),
                reason: reason.clone(),
}),
            Reducer::TicketremoteMemberConfirmControlCodeBrowserCapture{
                ticket_id,
                backend_id,
                session_id,
                request_id,
                candidate_frame_epoch,
                candidate_frame_sequence,
                accepted_reason,
}             => __sats::bsatn::to_vec(&ticketremote_member_confirm_control_code_browser_capture_reducer::TicketremoteMemberConfirmControlCodeBrowserCaptureArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                session_id: session_id.clone(),
                request_id: request_id.clone(),
                candidate_frame_epoch: candidate_frame_epoch.clone(),
                candidate_frame_sequence: candidate_frame_sequence.clone(),
                accepted_reason: accepted_reason.clone(),
}),
            Reducer::TicketremoteMemberExtendControl{
                ticket_id,
}             => __sats::bsatn::to_vec(&ticketremote_member_extend_control_reducer::TicketremoteMemberExtendControlArgs {
                ticket_id: ticket_id.clone(),
}),
            Reducer::TicketremoteMemberPrepareControlCode{
                ticket_id,
                backend_id,
                reason,
}             => __sats::bsatn::to_vec(&ticketremote_member_prepare_control_code_reducer::TicketremoteMemberPrepareControlCodeArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                reason: reason.clone(),
}),
            Reducer::TicketremoteMemberRecoverStream{
                ticket_id,
                backend_id,
                reason,
}             => __sats::bsatn::to_vec(&ticketremote_member_recover_stream_reducer::TicketremoteMemberRecoverStreamArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                reason: reason.clone(),
}),
            Reducer::TicketremoteMemberReleaseControl{
                ticket_id,
                reason,
}             => __sats::bsatn::to_vec(&ticketremote_member_release_control_reducer::TicketremoteMemberReleaseControlArgs {
                ticket_id: ticket_id.clone(),
                reason: reason.clone(),
}),
            Reducer::TicketremoteMemberRemoveMember{
                ticket_id,
                email,
}             => __sats::bsatn::to_vec(&ticketremote_member_remove_member_reducer::TicketremoteMemberRemoveMemberArgs {
                ticket_id: ticket_id.clone(),
                email: email.clone(),
}),
            Reducer::TicketremoteMemberRequestControlCode{
                ticket_id,
                backend_id,
                session_id,
                digits,
}             => __sats::bsatn::to_vec(&ticketremote_member_request_control_code_reducer::TicketremoteMemberRequestControlCodeArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                session_id: session_id.clone(),
                digits: digits.clone(),
}),
            Reducer::TicketremoteMemberRequestKeyframe{
                ticket_id,
                backend_id,
                reason,
}             => __sats::bsatn::to_vec(&ticketremote_member_request_keyframe_reducer::TicketremoteMemberRequestKeyframeArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                reason: reason.clone(),
}),
            Reducer::TicketremoteMemberRevokeControl{
                ticket_id,
                reason,
}             => __sats::bsatn::to_vec(&ticketremote_member_revoke_control_reducer::TicketremoteMemberRevokeControlArgs {
                ticket_id: ticket_id.clone(),
                reason: reason.clone(),
}),
            Reducer::TicketremoteMemberSetStreamFocus{
                ticket_id,
                backend_id,
                session_id,
                active,
                reason,
}             => __sats::bsatn::to_vec(&ticketremote_member_set_stream_focus_reducer::TicketremoteMemberSetStreamFocusArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                session_id: session_id.clone(),
                active: active.clone(),
                reason: reason.clone(),
}),
            Reducer::TicketremoteMemberUpsertMember{
                ticket_id,
                email,
                role,
}             => __sats::bsatn::to_vec(&ticketremote_member_upsert_member_reducer::TicketremoteMemberUpsertMemberArgs {
                ticket_id: ticket_id.clone(),
                email: email.clone(),
                role: role.clone(),
}),
            Reducer::TicketremotePurgeExpiredStreamCommands{
                ticket_id,
                now_arg,
                batch_size,
}             => __sats::bsatn::to_vec(&ticketremote_purge_expired_stream_commands_reducer::TicketremotePurgeExpiredStreamCommandsArgs {
                ticket_id: ticket_id.clone(),
                now_arg: now_arg.clone(),
                batch_size: batch_size.clone(),
}),
            Reducer::TicketremoteRegisterServiceIdentity{
                ticket_id,
                now,
}             => __sats::bsatn::to_vec(&ticketremote_register_service_identity_reducer::TicketremoteRegisterServiceIdentityArgs {
                ticket_id: ticket_id.clone(),
                now: now.clone(),
}),
            Reducer::TicketremoteReleaseControl{
                ticket_id,
                session_id,
                email,
                reason,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_release_control_reducer::TicketremoteReleaseControlArgs {
                ticket_id: ticket_id.clone(),
                session_id: session_id.clone(),
                email: email.clone(),
                reason: reason.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteRemoveMember{
                ticket_id,
                actor_email,
                email,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_remove_member_reducer::TicketremoteRemoveMemberArgs {
                ticket_id: ticket_id.clone(),
                actor_email: actor_email.clone(),
                email: email.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteRevokeControl{
                ticket_id,
                actor_email,
                reason,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_revoke_control_reducer::TicketremoteRevokeControlArgs {
                ticket_id: ticket_id.clone(),
                actor_email: actor_email.clone(),
                reason: reason.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteServiceBootstrap{
                ticket_id,
                display_name,
                admin_email,
                phone_backend_id,
                phone_base_url,
                phone_attach_name,
                auth_issuer,
                auth_audience,
}             => __sats::bsatn::to_vec(&ticketremote_service_bootstrap_reducer::TicketremoteServiceBootstrapArgs {
                ticket_id: ticket_id.clone(),
                display_name: display_name.clone(),
                admin_email: admin_email.clone(),
                phone_backend_id: phone_backend_id.clone(),
                phone_base_url: phone_base_url.clone(),
                phone_attach_name: phone_attach_name.clone(),
                auth_issuer: auth_issuer.clone(),
                auth_audience: auth_audience.clone(),
}),
            Reducer::TicketremoteSetDevPerfMetrics{
                ticket_id,
                enabled,
                reason,
                expires_at,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_set_dev_perf_metrics_reducer::TicketremoteSetDevPerfMetricsArgs {
                ticket_id: ticket_id.clone(),
                enabled: enabled.clone(),
                reason: reason.clone(),
                expires_at: expires_at.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteSetStreamDesiredState{
                ticket_id,
                backend_id,
                desired_active,
                viewer_count,
                reason,
                revision,
                updated_by,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_set_stream_desired_state_reducer::TicketremoteSetStreamDesiredStateArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                desired_active: desired_active.clone(),
                viewer_count: viewer_count.clone(),
                reason: reason.clone(),
                revision: revision.clone(),
                updated_by: updated_by.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteSnapshotRuntimeTablesToLogs{
                ticket_id,
                now_arg,
                batch_size,
}             => __sats::bsatn::to_vec(&ticketremote_snapshot_runtime_tables_to_logs_reducer::TicketremoteSnapshotRuntimeTablesToLogsArgs {
                ticket_id: ticket_id.clone(),
                now_arg: now_arg.clone(),
                batch_size: batch_size.clone(),
}),
            Reducer::TicketremoteUpdateControlCodeRequest{
                ticket_id,
                request_id,
                status,
                reason,
                message,
                stream_epoch,
                frame_sequence,
                min_frame_sequence,
                result_frame_epoch,
                result_min_frame_sequence,
                result_proof,
                result_proof_at,
                cleanup_pending,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_update_control_code_request_reducer::TicketremoteUpdateControlCodeRequestArgs {
                ticket_id: ticket_id.clone(),
                request_id: request_id.clone(),
                status: status.clone(),
                reason: reason.clone(),
                message: message.clone(),
                stream_epoch: stream_epoch.clone(),
                frame_sequence: frame_sequence.clone(),
                min_frame_sequence: min_frame_sequence.clone(),
                result_frame_epoch: result_frame_epoch.clone(),
                result_min_frame_sequence: result_min_frame_sequence.clone(),
                result_proof: result_proof.clone(),
                result_proof_at: result_proof_at.clone(),
                cleanup_pending: cleanup_pending.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteUpdatePhone{
                ticket_id,
                backend_id,
                attach_name,
                base_url,
                desired_state,
                health_json,
                last_error,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_update_phone_reducer::TicketremoteUpdatePhoneArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                attach_name: attach_name.clone(),
                base_url: base_url.clone(),
                desired_state: desired_state.clone(),
                health_json: health_json.clone(),
                last_error: last_error.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteUpdatePhoneCurrentReport{
                ticket_id,
                backend_id,
                stream_state,
                desired_active,
                last_command_id,
                last_command_revision,
                status_json,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_update_phone_current_report_reducer::TicketremoteUpdatePhoneCurrentReportArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                stream_state: stream_state.clone(),
                desired_active: desired_active.clone(),
                last_command_id: last_command_id.clone(),
                last_command_revision: last_command_revision.clone(),
                status_json: status_json.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteUpdatePhoneStatus{
                ticket_id,
                backend_id,
                attach_name,
                base_url,
                desired_state,
                health_json,
                last_error,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_update_phone_status_reducer::TicketremoteUpdatePhoneStatusArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                attach_name: attach_name.clone(),
                base_url: base_url.clone(),
                desired_state: desired_state.clone(),
                health_json: health_json.clone(),
                last_error: last_error.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteUpdateRelayCurrentReport{
                ticket_id,
                backend_id,
                video_clients,
                stream_verdict,
                last_frame_ago_millis,
                frames_forwarded,
                status_json,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_update_relay_current_report_reducer::TicketremoteUpdateRelayCurrentReportArgs {
                ticket_id: ticket_id.clone(),
                backend_id: backend_id.clone(),
                video_clients: video_clients.clone(),
                stream_verdict: stream_verdict.clone(),
                last_frame_ago_millis: last_frame_ago_millis.clone(),
                frames_forwarded: frames_forwarded.clone(),
                status_json: status_json.clone(),
                now_arg: now_arg.clone(),
}),
            Reducer::TicketremoteUpsertMember{
                ticket_id,
                actor_email,
                email,
                role,
                now_arg,
}             => __sats::bsatn::to_vec(&ticketremote_upsert_member_reducer::TicketremoteUpsertMemberArgs {
                ticket_id: ticket_id.clone(),
                actor_email: actor_email.clone(),
                email: email.clone(),
                role: role.clone(),
                now_arg: now_arg.clone(),
}),
            _ => unreachable!(),
}
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    ticketremote_control_code_request: __sdk::TableUpdate<TicketremoteControlCodeRequest>,
    ticketremote_phone_current_report: __sdk::TableUpdate<TicketremotePhoneCurrentReport>,
    ticketremote_phone_status: __sdk::TableUpdate<TicketremotePhoneStatus>,
    ticketremote_relay_current_report: __sdk::TableUpdate<TicketremoteRelayCurrentReport>,
    ticketremote_service_control_session: __sdk::TableUpdate<TicketremoteServiceControl>,
    ticketremote_service_phone_backend: __sdk::TableUpdate<TicketremoteServicePhone>,
    ticketremote_service_safe_operational_log:
        __sdk::TableUpdate<TicketremoteServiceSafeOperationalLog>,
    ticketremote_service_stream_command: __sdk::TableUpdate<TicketremoteServiceStreamCommand>,
    ticketremote_service_ticket: __sdk::TableUpdate<TicketremoteServiceTicket>,
    ticketremote_service_ticket_member: __sdk::TableUpdate<TicketremoteServiceMember>,
    ticketremote_service_viewer_presence: __sdk::TableUpdate<TicketremoteServiceViewer>,
    ticketremote_stream_command_signal: __sdk::TableUpdate<TicketremoteStreamCommandSignal>,
    ticketremote_stream_desired_state: __sdk::TableUpdate<TicketremoteStreamDesiredState>,
    ticketremote_ticket_summary: __sdk::TableUpdate<TicketremoteTicketSummary>,
    ticketremote_viewer_public: __sdk::TableUpdate<TicketremoteViewerPublic>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "ticketremote_control_code_request" => {
                    db_update.ticketremote_control_code_request.append(
                        ticketremote_control_code_request_table::parse_table_update(table_update)?,
                    )
                }
                "ticketremote_phone_current_report" => {
                    db_update.ticketremote_phone_current_report.append(
                        ticketremote_phone_current_report_table::parse_table_update(table_update)?,
                    )
                }
                "ticketremote_phone_status" => db_update.ticketremote_phone_status.append(
                    ticketremote_phone_status_table::parse_table_update(table_update)?,
                ),
                "ticketremote_relay_current_report" => {
                    db_update.ticketremote_relay_current_report.append(
                        ticketremote_relay_current_report_table::parse_table_update(table_update)?,
                    )
                }
                "ticketremote_service_control_session" => {
                    db_update.ticketremote_service_control_session.append(
                        ticketremote_service_control_session_table::parse_table_update(
                            table_update,
                        )?,
                    )
                }
                "ticketremote_service_phone_backend" => {
                    db_update.ticketremote_service_phone_backend.append(
                        ticketremote_service_phone_backend_table::parse_table_update(table_update)?,
                    )
                }
                "ticketremote_service_safe_operational_log" => {
                    db_update.ticketremote_service_safe_operational_log.append(
                        ticketremote_service_safe_operational_log_table::parse_table_update(
                            table_update,
                        )?,
                    )
                }
                "ticketremote_service_stream_command" => {
                    db_update.ticketremote_service_stream_command.append(
                        ticketremote_service_stream_command_table::parse_table_update(
                            table_update,
                        )?,
                    )
                }
                "ticketremote_service_ticket" => db_update.ticketremote_service_ticket.append(
                    ticketremote_service_ticket_table::parse_table_update(table_update)?,
                ),
                "ticketremote_service_ticket_member" => {
                    db_update.ticketremote_service_ticket_member.append(
                        ticketremote_service_ticket_member_table::parse_table_update(table_update)?,
                    )
                }
                "ticketremote_service_viewer_presence" => {
                    db_update.ticketremote_service_viewer_presence.append(
                        ticketremote_service_viewer_presence_table::parse_table_update(
                            table_update,
                        )?,
                    )
                }
                "ticketremote_stream_command_signal" => {
                    db_update.ticketremote_stream_command_signal.append(
                        ticketremote_stream_command_signal_table::parse_table_update(table_update)?,
                    )
                }
                "ticketremote_stream_desired_state" => {
                    db_update.ticketremote_stream_desired_state.append(
                        ticketremote_stream_desired_state_table::parse_table_update(table_update)?,
                    )
                }
                "ticketremote_ticket_summary" => db_update.ticketremote_ticket_summary.append(
                    ticketremote_ticket_summary_table::parse_table_update(table_update)?,
                ),
                "ticketremote_viewer_public" => db_update.ticketremote_viewer_public.append(
                    ticketremote_viewer_public_table::parse_table_update(table_update)?,
                ),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.ticketremote_control_code_request = cache
            .apply_diff_to_table::<TicketremoteControlCodeRequest>(
                "ticketremote_control_code_request",
                &self.ticketremote_control_code_request,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_phone_current_report = cache
            .apply_diff_to_table::<TicketremotePhoneCurrentReport>(
                "ticketremote_phone_current_report",
                &self.ticketremote_phone_current_report,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_phone_status = cache
            .apply_diff_to_table::<TicketremotePhoneStatus>(
                "ticketremote_phone_status",
                &self.ticketremote_phone_status,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_relay_current_report = cache
            .apply_diff_to_table::<TicketremoteRelayCurrentReport>(
                "ticketremote_relay_current_report",
                &self.ticketremote_relay_current_report,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_stream_command_signal = cache
            .apply_diff_to_table::<TicketremoteStreamCommandSignal>(
                "ticketremote_stream_command_signal",
                &self.ticketremote_stream_command_signal,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_stream_desired_state = cache
            .apply_diff_to_table::<TicketremoteStreamDesiredState>(
                "ticketremote_stream_desired_state",
                &self.ticketremote_stream_desired_state,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_ticket_summary = cache
            .apply_diff_to_table::<TicketremoteTicketSummary>(
                "ticketremote_ticket_summary",
                &self.ticketremote_ticket_summary,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_viewer_public = cache
            .apply_diff_to_table::<TicketremoteViewerPublic>(
                "ticketremote_viewer_public",
                &self.ticketremote_viewer_public,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_service_control_session = cache
            .apply_diff_to_table::<TicketremoteServiceControl>(
                "ticketremote_service_control_session",
                &self.ticketremote_service_control_session,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_service_phone_backend = cache
            .apply_diff_to_table::<TicketremoteServicePhone>(
                "ticketremote_service_phone_backend",
                &self.ticketremote_service_phone_backend,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_service_safe_operational_log = cache
            .apply_diff_to_table::<TicketremoteServiceSafeOperationalLog>(
                "ticketremote_service_safe_operational_log",
                &self.ticketremote_service_safe_operational_log,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_service_stream_command = cache
            .apply_diff_to_table::<TicketremoteServiceStreamCommand>(
                "ticketremote_service_stream_command",
                &self.ticketremote_service_stream_command,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_service_ticket = cache
            .apply_diff_to_table::<TicketremoteServiceTicket>(
                "ticketremote_service_ticket",
                &self.ticketremote_service_ticket,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_service_ticket_member = cache
            .apply_diff_to_table::<TicketremoteServiceMember>(
                "ticketremote_service_ticket_member",
                &self.ticketremote_service_ticket_member,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.ticketremote_service_viewer_presence = cache
            .apply_diff_to_table::<TicketremoteServiceViewer>(
                "ticketremote_service_viewer_presence",
                &self.ticketremote_service_viewer_presence,
            )
            .with_updates_by_pk(|row| &row.session_id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "ticketremote_control_code_request" => db_update
                    .ticketremote_control_code_request
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_phone_current_report" => db_update
                    .ticketremote_phone_current_report
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_phone_status" => db_update
                    .ticketremote_phone_status
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_relay_current_report" => db_update
                    .ticketremote_relay_current_report
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_service_control_session" => db_update
                    .ticketremote_service_control_session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_service_phone_backend" => db_update
                    .ticketremote_service_phone_backend
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_service_safe_operational_log" => db_update
                    .ticketremote_service_safe_operational_log
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_service_stream_command" => db_update
                    .ticketremote_service_stream_command
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_service_ticket" => db_update
                    .ticketremote_service_ticket
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_service_ticket_member" => db_update
                    .ticketremote_service_ticket_member
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_service_viewer_presence" => db_update
                    .ticketremote_service_viewer_presence
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_stream_command_signal" => db_update
                    .ticketremote_stream_command_signal
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_stream_desired_state" => db_update
                    .ticketremote_stream_desired_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_ticket_summary" => db_update
                    .ticketremote_ticket_summary
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ticketremote_viewer_public" => db_update
                    .ticketremote_viewer_public
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "ticketremote_control_code_request" => db_update
                    .ticketremote_control_code_request
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_phone_current_report" => db_update
                    .ticketremote_phone_current_report
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_phone_status" => db_update
                    .ticketremote_phone_status
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_relay_current_report" => db_update
                    .ticketremote_relay_current_report
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_service_control_session" => db_update
                    .ticketremote_service_control_session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_service_phone_backend" => db_update
                    .ticketremote_service_phone_backend
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_service_safe_operational_log" => db_update
                    .ticketremote_service_safe_operational_log
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_service_stream_command" => db_update
                    .ticketremote_service_stream_command
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_service_ticket" => db_update
                    .ticketremote_service_ticket
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_service_ticket_member" => db_update
                    .ticketremote_service_ticket_member
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_service_viewer_presence" => db_update
                    .ticketremote_service_viewer_presence
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_stream_command_signal" => db_update
                    .ticketremote_stream_command_signal
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_stream_desired_state" => db_update
                    .ticketremote_stream_desired_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_ticket_summary" => db_update
                    .ticketremote_ticket_summary
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ticketremote_viewer_public" => db_update
                    .ticketremote_viewer_public
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    ticketremote_control_code_request: __sdk::TableAppliedDiff<'r, TicketremoteControlCodeRequest>,
    ticketremote_phone_current_report: __sdk::TableAppliedDiff<'r, TicketremotePhoneCurrentReport>,
    ticketremote_phone_status: __sdk::TableAppliedDiff<'r, TicketremotePhoneStatus>,
    ticketremote_relay_current_report: __sdk::TableAppliedDiff<'r, TicketremoteRelayCurrentReport>,
    ticketremote_service_control_session: __sdk::TableAppliedDiff<'r, TicketremoteServiceControl>,
    ticketremote_service_phone_backend: __sdk::TableAppliedDiff<'r, TicketremoteServicePhone>,
    ticketremote_service_safe_operational_log:
        __sdk::TableAppliedDiff<'r, TicketremoteServiceSafeOperationalLog>,
    ticketremote_service_stream_command:
        __sdk::TableAppliedDiff<'r, TicketremoteServiceStreamCommand>,
    ticketremote_service_ticket: __sdk::TableAppliedDiff<'r, TicketremoteServiceTicket>,
    ticketremote_service_ticket_member: __sdk::TableAppliedDiff<'r, TicketremoteServiceMember>,
    ticketremote_service_viewer_presence: __sdk::TableAppliedDiff<'r, TicketremoteServiceViewer>,
    ticketremote_stream_command_signal:
        __sdk::TableAppliedDiff<'r, TicketremoteStreamCommandSignal>,
    ticketremote_stream_desired_state: __sdk::TableAppliedDiff<'r, TicketremoteStreamDesiredState>,
    ticketremote_ticket_summary: __sdk::TableAppliedDiff<'r, TicketremoteTicketSummary>,
    ticketremote_viewer_public: __sdk::TableAppliedDiff<'r, TicketremoteViewerPublic>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<TicketremoteControlCodeRequest>(
            "ticketremote_control_code_request",
            &self.ticketremote_control_code_request,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremotePhoneCurrentReport>(
            "ticketremote_phone_current_report",
            &self.ticketremote_phone_current_report,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremotePhoneStatus>(
            "ticketremote_phone_status",
            &self.ticketremote_phone_status,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteRelayCurrentReport>(
            "ticketremote_relay_current_report",
            &self.ticketremote_relay_current_report,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteServiceControl>(
            "ticketremote_service_control_session",
            &self.ticketremote_service_control_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteServicePhone>(
            "ticketremote_service_phone_backend",
            &self.ticketremote_service_phone_backend,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteServiceSafeOperationalLog>(
            "ticketremote_service_safe_operational_log",
            &self.ticketremote_service_safe_operational_log,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteServiceStreamCommand>(
            "ticketremote_service_stream_command",
            &self.ticketremote_service_stream_command,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteServiceTicket>(
            "ticketremote_service_ticket",
            &self.ticketremote_service_ticket,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteServiceMember>(
            "ticketremote_service_ticket_member",
            &self.ticketremote_service_ticket_member,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteServiceViewer>(
            "ticketremote_service_viewer_presence",
            &self.ticketremote_service_viewer_presence,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteStreamCommandSignal>(
            "ticketremote_stream_command_signal",
            &self.ticketremote_stream_command_signal,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteStreamDesiredState>(
            "ticketremote_stream_desired_state",
            &self.ticketremote_stream_desired_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteTicketSummary>(
            "ticketremote_ticket_summary",
            &self.ticketremote_ticket_summary,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TicketremoteViewerPublic>(
            "ticketremote_viewer_public",
            &self.ticketremote_viewer_public,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        ticketremote_control_code_request_table::register_table(client_cache);
        ticketremote_phone_current_report_table::register_table(client_cache);
        ticketremote_phone_status_table::register_table(client_cache);
        ticketremote_relay_current_report_table::register_table(client_cache);
        ticketremote_service_control_session_table::register_table(client_cache);
        ticketremote_service_phone_backend_table::register_table(client_cache);
        ticketremote_service_safe_operational_log_table::register_table(client_cache);
        ticketremote_service_stream_command_table::register_table(client_cache);
        ticketremote_service_ticket_table::register_table(client_cache);
        ticketremote_service_ticket_member_table::register_table(client_cache);
        ticketremote_service_viewer_presence_table::register_table(client_cache);
        ticketremote_stream_command_signal_table::register_table(client_cache);
        ticketremote_stream_desired_state_table::register_table(client_cache);
        ticketremote_ticket_summary_table::register_table(client_cache);
        ticketremote_viewer_public_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "ticketremote_control_code_request",
        "ticketremote_phone_current_report",
        "ticketremote_phone_status",
        "ticketremote_relay_current_report",
        "ticketremote_service_control_session",
        "ticketremote_service_phone_backend",
        "ticketremote_service_safe_operational_log",
        "ticketremote_service_stream_command",
        "ticketremote_service_ticket",
        "ticketremote_service_ticket_member",
        "ticketremote_service_viewer_presence",
        "ticketremote_stream_command_signal",
        "ticketremote_stream_desired_state",
        "ticketremote_ticket_summary",
        "ticketremote_viewer_public",
    ];
}
