// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteTrainCheckin {
    pub id: String,
    pub ticket_id: String,
    pub email: String,
    pub request_id: String,
    pub direction: String,
    pub carriage: u8,
    pub checked_in_at_ms: i64,
    pub active_until_ms: i64,
    pub history_until_ms: i64,
    pub status: String,
}

impl __sdk::InModule for TicketremoteTrainCheckin {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteTrainCheckin`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteTrainCheckinCols {
    pub id: __sdk::__query_builder::Col<TicketremoteTrainCheckin, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteTrainCheckin, String>,
    pub email: __sdk::__query_builder::Col<TicketremoteTrainCheckin, String>,
    pub request_id: __sdk::__query_builder::Col<TicketremoteTrainCheckin, String>,
    pub direction: __sdk::__query_builder::Col<TicketremoteTrainCheckin, String>,
    pub carriage: __sdk::__query_builder::Col<TicketremoteTrainCheckin, u8>,
    pub checked_in_at_ms: __sdk::__query_builder::Col<TicketremoteTrainCheckin, i64>,
    pub active_until_ms: __sdk::__query_builder::Col<TicketremoteTrainCheckin, i64>,
    pub history_until_ms: __sdk::__query_builder::Col<TicketremoteTrainCheckin, i64>,
    pub status: __sdk::__query_builder::Col<TicketremoteTrainCheckin, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteTrainCheckin {
    type Cols = TicketremoteTrainCheckinCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteTrainCheckinCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            direction: __sdk::__query_builder::Col::new(table_name, "direction"),
            carriage: __sdk::__query_builder::Col::new(table_name, "carriage"),
            checked_in_at_ms: __sdk::__query_builder::Col::new(table_name, "checked_in_at_ms"),
            active_until_ms: __sdk::__query_builder::Col::new(table_name, "active_until_ms"),
            history_until_ms: __sdk::__query_builder::Col::new(table_name, "history_until_ms"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteTrainCheckin`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteTrainCheckinIxCols {
    pub id: __sdk::__query_builder::IxCol<TicketremoteTrainCheckin, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteTrainCheckin, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteTrainCheckin {
    type IxCols = TicketremoteTrainCheckinIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteTrainCheckinIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteTrainCheckin {}
