// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteOwnerRequestViviReauthFullResetArgs {
    pub version: u32,
    pub ticket_id: String,
    pub backend_id: String,
    pub request_id: String,
    pub credential_revision: String,
}

impl From<TicketremoteOwnerRequestViviReauthFullResetArgs> for super::Reducer {
    fn from(args: TicketremoteOwnerRequestViviReauthFullResetArgs) -> Self {
        Self::TicketremoteOwnerRequestViviReauthFullReset {
            version: args.version,
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            request_id: args.request_id,
            credential_revision: args.credential_revision,
        }
    }
}

impl __sdk::InModule for TicketremoteOwnerRequestViviReauthFullResetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_owner_request_vivi_reauth_full_reset`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_owner_request_vivi_reauth_full_reset {
    /// Request that the remote module invoke the reducer `ticketremote_owner_request_vivi_reauth_full_reset` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_owner_request_vivi_reauth_full_reset:ticketremote_owner_request_vivi_reauth_full_reset_then`] to run a callback after the reducer completes.
    fn ticketremote_owner_request_vivi_reauth_full_reset(
        &self,
        version: u32,
        ticket_id: String,
        backend_id: String,
        request_id: String,
        credential_revision: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_owner_request_vivi_reauth_full_reset_then(
            version,
            ticket_id,
            backend_id,
            request_id,
            credential_revision,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_owner_request_vivi_reauth_full_reset` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_owner_request_vivi_reauth_full_reset_then(
        &self,
        version: u32,
        ticket_id: String,
        backend_id: String,
        request_id: String,
        credential_revision: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_owner_request_vivi_reauth_full_reset for super::RemoteReducers {
    fn ticketremote_owner_request_vivi_reauth_full_reset_then(
        &self,
        version: u32,
        ticket_id: String,
        backend_id: String,
        request_id: String,
        credential_revision: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteOwnerRequestViviReauthFullResetArgs {
                version,
                ticket_id,
                backend_id,
                request_id,
                credential_revision,
            },
            callback,
        )
    }
}
