// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_push_delivery_type::TicketremotePushDelivery;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_service_push_delivery`.
///
/// Obtain a handle from the [`TicketremoteServicePushDeliveryTableAccess::ticketremote_service_push_delivery`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_service_push_delivery()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_push_delivery().on_insert(...)`.
pub struct TicketremoteServicePushDeliveryTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremotePushDelivery>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_service_push_delivery`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteServicePushDeliveryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteServicePushDeliveryTableHandle`], which mediates access to the table `ticketremote_service_push_delivery`.
    fn ticketremote_service_push_delivery(&self) -> TicketremoteServicePushDeliveryTableHandle<'_>;
}

impl TicketremoteServicePushDeliveryTableAccess for super::RemoteTables {
    fn ticketremote_service_push_delivery(&self) -> TicketremoteServicePushDeliveryTableHandle<'_> {
        TicketremoteServicePushDeliveryTableHandle {
            imp: self
                .imp
                .get_table::<TicketremotePushDelivery>("ticketremote_service_push_delivery"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteServicePushDeliveryInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteServicePushDeliveryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteServicePushDeliveryTableHandle<'ctx> {
    type Row = TicketremotePushDelivery;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremotePushDelivery> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteServicePushDeliveryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServicePushDeliveryInsertCallbackId {
        TicketremoteServicePushDeliveryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteServicePushDeliveryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteServicePushDeliveryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServicePushDeliveryDeleteCallbackId {
        TicketremoteServicePushDeliveryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteServicePushDeliveryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteServicePushDeliveryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteServicePushDeliveryTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteServicePushDeliveryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteServicePushDeliveryUpdateCallbackId {
        TicketremoteServicePushDeliveryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteServicePushDeliveryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_service_push_delivery`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteServicePushDeliveryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_push_delivery().id().find(...)`.
pub struct TicketremoteServicePushDeliveryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremotePushDelivery, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteServicePushDeliveryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_service_push_delivery`.
    pub fn id(&self) -> TicketremoteServicePushDeliveryIdUnique<'ctx> {
        TicketremoteServicePushDeliveryIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteServicePushDeliveryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremotePushDelivery> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremotePushDelivery>("ticketremote_service_push_delivery");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremotePushDelivery>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TicketremotePushDelivery>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremotePushDelivery`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_service_push_deliveryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremotePushDelivery`.
    fn ticketremote_service_push_delivery(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremotePushDelivery>;
}

impl ticketremote_service_push_deliveryQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_service_push_delivery(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremotePushDelivery> {
        __sdk::__query_builder::Table::new("ticketremote_service_push_delivery")
    }
}
