// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteAppendStreamCommandArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub command_id: String,
    pub command_type: String,
    pub revision: String,
    pub reason: String,
    pub payload_json: String,
    pub ttl_millis: u32,
    pub now_arg: String,
}

impl From<TicketremoteAppendStreamCommandArgs> for super::Reducer {
    fn from(args: TicketremoteAppendStreamCommandArgs) -> Self {
        Self::TicketremoteAppendStreamCommand {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            command_id: args.command_id,
            command_type: args.command_type,
            revision: args.revision,
            reason: args.reason,
            payload_json: args.payload_json,
            ttl_millis: args.ttl_millis,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteAppendStreamCommandArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_append_stream_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_append_stream_command {
    /// Request that the remote module invoke the reducer `ticketremote_append_stream_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_append_stream_command:ticketremote_append_stream_command_then`] to run a callback after the reducer completes.
    fn ticketremote_append_stream_command(
        &self,
        ticket_id: String,
        backend_id: String,
        command_id: String,
        command_type: String,
        revision: String,
        reason: String,
        payload_json: String,
        ttl_millis: u32,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_append_stream_command_then(
            ticket_id,
            backend_id,
            command_id,
            command_type,
            revision,
            reason,
            payload_json,
            ttl_millis,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_append_stream_command` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_append_stream_command_then(
        &self,
        ticket_id: String,
        backend_id: String,
        command_id: String,
        command_type: String,
        revision: String,
        reason: String,
        payload_json: String,
        ttl_millis: u32,
        now_arg: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_append_stream_command for super::RemoteReducers {
    fn ticketremote_append_stream_command_then(
        &self,
        ticket_id: String,
        backend_id: String,
        command_id: String,
        command_type: String,
        revision: String,
        reason: String,
        payload_json: String,
        ttl_millis: u32,
        now_arg: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteAppendStreamCommandArgs {
                ticket_id,
                backend_id,
                command_id,
                command_type,
                revision,
                reason,
                payload_json,
                ttl_millis,
                now_arg,
            },
            callback,
        )
    }
}
