// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteMemberDailyActions {
    pub id: String,
    pub ticket_id: String,
    pub account_scope_id: String,
    pub day: String,
    pub registration_attempts: Vec<u32>,
    pub registration_successes: Vec<u32>,
    pub control_code_attempts: Vec<u32>,
    pub control_code_successes: Vec<u32>,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteMemberDailyActions {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteMemberDailyActions`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteMemberDailyActionsCols {
    pub id: __sdk::__query_builder::Col<TicketremoteMemberDailyActions, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteMemberDailyActions, String>,
    pub account_scope_id: __sdk::__query_builder::Col<TicketremoteMemberDailyActions, String>,
    pub day: __sdk::__query_builder::Col<TicketremoteMemberDailyActions, String>,
    pub registration_attempts:
        __sdk::__query_builder::Col<TicketremoteMemberDailyActions, Vec<u32>>,
    pub registration_successes:
        __sdk::__query_builder::Col<TicketremoteMemberDailyActions, Vec<u32>>,
    pub control_code_attempts:
        __sdk::__query_builder::Col<TicketremoteMemberDailyActions, Vec<u32>>,
    pub control_code_successes:
        __sdk::__query_builder::Col<TicketremoteMemberDailyActions, Vec<u32>>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteMemberDailyActions, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteMemberDailyActions {
    type Cols = TicketremoteMemberDailyActionsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteMemberDailyActionsCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            account_scope_id: __sdk::__query_builder::Col::new(table_name, "account_scope_id"),
            day: __sdk::__query_builder::Col::new(table_name, "day"),
            registration_attempts: __sdk::__query_builder::Col::new(
                table_name,
                "registration_attempts",
            ),
            registration_successes: __sdk::__query_builder::Col::new(
                table_name,
                "registration_successes",
            ),
            control_code_attempts: __sdk::__query_builder::Col::new(
                table_name,
                "control_code_attempts",
            ),
            control_code_successes: __sdk::__query_builder::Col::new(
                table_name,
                "control_code_successes",
            ),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteMemberDailyActions`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteMemberDailyActionsIxCols {
    pub id: __sdk::__query_builder::IxCol<TicketremoteMemberDailyActions, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteMemberDailyActions {
    type IxCols = TicketremoteMemberDailyActionsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteMemberDailyActionsIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteMemberDailyActions {}
