// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteLatestTicketReselectSchedule {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub scheduled_at: String,
    pub phone_local_time: String,
    pub phone_time_zone: String,
    pub status: String,
    pub command_id: String,
    pub result_reason: String,
    pub result_phase: String,
    pub proof_source: String,
    pub requested_by: String,
    pub created_at: String,
    pub updated_at: String,
    pub triggered_at: String,
    pub completed_at: String,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteLatestTicketReselectSchedule {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteLatestTicketReselectSchedule`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteLatestTicketReselectScheduleCols {
    pub id: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub scheduled_at: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub phone_local_time:
        __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub phone_time_zone:
        __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub status: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub command_id: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub result_reason:
        __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub result_phase: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub proof_source: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub requested_by: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub created_at: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub triggered_at: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub completed_at: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteLatestTicketReselectSchedule, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteLatestTicketReselectSchedule {
    type Cols = TicketremoteLatestTicketReselectScheduleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteLatestTicketReselectScheduleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            phone_local_time: __sdk::__query_builder::Col::new(table_name, "phone_local_time"),
            phone_time_zone: __sdk::__query_builder::Col::new(table_name, "phone_time_zone"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            command_id: __sdk::__query_builder::Col::new(table_name, "command_id"),
            result_reason: __sdk::__query_builder::Col::new(table_name, "result_reason"),
            result_phase: __sdk::__query_builder::Col::new(table_name, "result_phase"),
            proof_source: __sdk::__query_builder::Col::new(table_name, "proof_source"),
            requested_by: __sdk::__query_builder::Col::new(table_name, "requested_by"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            triggered_at: __sdk::__query_builder::Col::new(table_name, "triggered_at"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteLatestTicketReselectSchedule`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteLatestTicketReselectScheduleIxCols {
    pub backend_id: __sdk::__query_builder::IxCol<TicketremoteLatestTicketReselectSchedule, String>,
    pub command_id: __sdk::__query_builder::IxCol<TicketremoteLatestTicketReselectSchedule, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteLatestTicketReselectSchedule, String>,
    pub status: __sdk::__query_builder::IxCol<TicketremoteLatestTicketReselectSchedule, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteLatestTicketReselectSchedule, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteLatestTicketReselectSchedule {
    type IxCols = TicketremoteLatestTicketReselectScheduleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteLatestTicketReselectScheduleIxCols {
            backend_id: __sdk::__query_builder::IxCol::new(table_name, "backend_id"),
            command_id: __sdk::__query_builder::IxCol::new(table_name, "command_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteLatestTicketReselectSchedule {}
