// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteViviCredentials {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub email: String,
    pub password: String,
    pub revision: String,
    pub created_at: String,
    pub updated_at: String,
}

impl __sdk::InModule for TicketremoteViviCredentials {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteViviCredentials`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteViviCredentialsCols {
    pub id: __sdk::__query_builder::Col<TicketremoteViviCredentials, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteViviCredentials, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteViviCredentials, String>,
    pub email: __sdk::__query_builder::Col<TicketremoteViviCredentials, String>,
    pub password: __sdk::__query_builder::Col<TicketremoteViviCredentials, String>,
    pub revision: __sdk::__query_builder::Col<TicketremoteViviCredentials, String>,
    pub created_at: __sdk::__query_builder::Col<TicketremoteViviCredentials, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteViviCredentials, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteViviCredentials {
    type Cols = TicketremoteViviCredentialsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteViviCredentialsCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            password: __sdk::__query_builder::Col::new(table_name, "password"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteViviCredentials`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteViviCredentialsIxCols {
    pub backend_id: __sdk::__query_builder::IxCol<TicketremoteViviCredentials, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteViviCredentials, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteViviCredentials, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteViviCredentials {
    type IxCols = TicketremoteViviCredentialsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteViviCredentialsIxCols {
            backend_id: __sdk::__query_builder::IxCol::new(table_name, "backend_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteViviCredentials {}
