// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremotePublishPhoneControlStateArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub session_id: String,
    pub context_revision: String,
    pub observation_sequence: u64,
    pub view: String,
    pub ready: bool,
    pub busy: bool,
    pub reason: String,
    pub left_basis_points: u32,
    pub top_basis_points: u32,
    pub right_basis_points: u32,
    pub bottom_basis_points: u32,
    pub observed_at: String,
}

impl From<TicketremotePublishPhoneControlStateArgs> for super::Reducer {
    fn from(args: TicketremotePublishPhoneControlStateArgs) -> Self {
        Self::TicketremotePublishPhoneControlState {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            session_id: args.session_id,
            context_revision: args.context_revision,
            observation_sequence: args.observation_sequence,
            view: args.view,
            ready: args.ready,
            busy: args.busy,
            reason: args.reason,
            left_basis_points: args.left_basis_points,
            top_basis_points: args.top_basis_points,
            right_basis_points: args.right_basis_points,
            bottom_basis_points: args.bottom_basis_points,
            observed_at: args.observed_at,
        }
    }
}

impl __sdk::InModule for TicketremotePublishPhoneControlStateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_publish_phone_control_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_publish_phone_control_state {
    /// Request that the remote module invoke the reducer `ticketremote_publish_phone_control_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_publish_phone_control_state:ticketremote_publish_phone_control_state_then`] to run a callback after the reducer completes.
    fn ticketremote_publish_phone_control_state(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        context_revision: String,
        observation_sequence: u64,
        view: String,
        ready: bool,
        busy: bool,
        reason: String,
        left_basis_points: u32,
        top_basis_points: u32,
        right_basis_points: u32,
        bottom_basis_points: u32,
        observed_at: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_publish_phone_control_state_then(
            ticket_id,
            backend_id,
            session_id,
            context_revision,
            observation_sequence,
            view,
            ready,
            busy,
            reason,
            left_basis_points,
            top_basis_points,
            right_basis_points,
            bottom_basis_points,
            observed_at,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_publish_phone_control_state` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_publish_phone_control_state_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        context_revision: String,
        observation_sequence: u64,
        view: String,
        ready: bool,
        busy: bool,
        reason: String,
        left_basis_points: u32,
        top_basis_points: u32,
        right_basis_points: u32,
        bottom_basis_points: u32,
        observed_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_publish_phone_control_state for super::RemoteReducers {
    fn ticketremote_publish_phone_control_state_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        context_revision: String,
        observation_sequence: u64,
        view: String,
        ready: bool,
        busy: bool,
        reason: String,
        left_basis_points: u32,
        top_basis_points: u32,
        right_basis_points: u32,
        bottom_basis_points: u32,
        observed_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremotePublishPhoneControlStateArgs {
                ticket_id,
                backend_id,
                session_id,
                context_revision,
                observation_sequence,
                view,
                ready,
                busy,
                reason,
                left_basis_points,
                top_basis_points,
                right_basis_points,
                bottom_basis_points,
                observed_at,
            },
            callback,
        )
    }
}
