// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_stream_viewer_focus_type::TicketremoteStreamViewerFocus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_privileged_viewers`.
///
/// Obtain a handle from the [`TicketremotePrivilegedViewersTableAccess::ticketremote_privileged_viewers`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_privileged_viewers()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_privileged_viewers().on_insert(...)`.
pub struct TicketremotePrivilegedViewersTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteStreamViewerFocus>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_privileged_viewers`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremotePrivilegedViewersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremotePrivilegedViewersTableHandle`], which mediates access to the table `ticketremote_privileged_viewers`.
    fn ticketremote_privileged_viewers(&self) -> TicketremotePrivilegedViewersTableHandle<'_>;
}

impl TicketremotePrivilegedViewersTableAccess for super::RemoteTables {
    fn ticketremote_privileged_viewers(&self) -> TicketremotePrivilegedViewersTableHandle<'_> {
        TicketremotePrivilegedViewersTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteStreamViewerFocus>("ticketremote_privileged_viewers"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremotePrivilegedViewersInsertCallbackId(__sdk::CallbackId);
pub struct TicketremotePrivilegedViewersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremotePrivilegedViewersTableHandle<'ctx> {
    type Row = TicketremoteStreamViewerFocus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteStreamViewerFocus> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremotePrivilegedViewersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremotePrivilegedViewersInsertCallbackId {
        TicketremotePrivilegedViewersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremotePrivilegedViewersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremotePrivilegedViewersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremotePrivilegedViewersDeleteCallbackId {
        TicketremotePrivilegedViewersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremotePrivilegedViewersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremotePrivilegedViewersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremotePrivilegedViewersTableHandle<'ctx> {
    type UpdateCallbackId = TicketremotePrivilegedViewersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremotePrivilegedViewersUpdateCallbackId {
        TicketremotePrivilegedViewersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremotePrivilegedViewersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_privileged_viewers`,
/// which allows point queries on the field of the same name
/// via the [`TicketremotePrivilegedViewersIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_privileged_viewers().id().find(...)`.
pub struct TicketremotePrivilegedViewersIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteStreamViewerFocus, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremotePrivilegedViewersTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_privileged_viewers`.
    pub fn id(&self) -> TicketremotePrivilegedViewersIdUnique<'ctx> {
        TicketremotePrivilegedViewersIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremotePrivilegedViewersIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteStreamViewerFocus> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremoteStreamViewerFocus>("ticketremote_privileged_viewers");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteStreamViewerFocus>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteStreamViewerFocus>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteStreamViewerFocus`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_privileged_viewersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteStreamViewerFocus`.
    fn ticketremote_privileged_viewers(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteStreamViewerFocus>;
}

impl ticketremote_privileged_viewersQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_privileged_viewers(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteStreamViewerFocus> {
        __sdk::__query_builder::Table::new("ticketremote_privileged_viewers")
    }
}
