// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberActivateTicketButtonArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub interaction_revision: String,
    pub control_id: String,
    pub input_sequence: String,
}

impl From<TicketremoteMemberActivateTicketButtonArgs> for super::Reducer {
    fn from(args: TicketremoteMemberActivateTicketButtonArgs) -> Self {
        Self::TicketremoteMemberActivateTicketButton {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            interaction_revision: args.interaction_revision,
            control_id: args.control_id,
            input_sequence: args.input_sequence,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberActivateTicketButtonArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_activate_ticket_button`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_activate_ticket_button {
    /// Request that the remote module invoke the reducer `ticketremote_member_activate_ticket_button` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_activate_ticket_button:ticketremote_member_activate_ticket_button_then`] to run a callback after the reducer completes.
    fn ticketremote_member_activate_ticket_button(
        &self,
        ticket_id: String,
        backend_id: String,
        interaction_revision: String,
        control_id: String,
        input_sequence: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_activate_ticket_button_then(
            ticket_id,
            backend_id,
            interaction_revision,
            control_id,
            input_sequence,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_activate_ticket_button` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_activate_ticket_button_then(
        &self,
        ticket_id: String,
        backend_id: String,
        interaction_revision: String,
        control_id: String,
        input_sequence: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_activate_ticket_button for super::RemoteReducers {
    fn ticketremote_member_activate_ticket_button_then(
        &self,
        ticket_id: String,
        backend_id: String,
        interaction_revision: String,
        control_id: String,
        input_sequence: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberActivateTicketButtonArgs {
                ticket_id,
                backend_id,
                interaction_revision,
                control_id,
                input_sequence,
            },
            callback,
        )
    }
}
