// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberSetHdrPreferenceArgs {
    pub ticket_id: String,
    pub enabled: bool,
}

impl From<TicketremoteMemberSetHdrPreferenceArgs> for super::Reducer {
    fn from(args: TicketremoteMemberSetHdrPreferenceArgs) -> Self {
        Self::TicketremoteMemberSetHdrPreference {
            ticket_id: args.ticket_id,
            enabled: args.enabled,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberSetHdrPreferenceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_set_hdr_preference`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_set_hdr_preference {
    /// Request that the remote module invoke the reducer `ticketremote_member_set_hdr_preference` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_set_hdr_preference:ticketremote_member_set_hdr_preference_then`] to run a callback after the reducer completes.
    fn ticketremote_member_set_hdr_preference(
        &self,
        ticket_id: String,
        enabled: bool,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_set_hdr_preference_then(ticket_id, enabled, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_set_hdr_preference` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_set_hdr_preference_then(
        &self,
        ticket_id: String,
        enabled: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_set_hdr_preference for super::RemoteReducers {
    fn ticketremote_member_set_hdr_preference_then(
        &self,
        ticket_id: String,
        enabled: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberSetHdrPreferenceArgs { ticket_id, enabled },
            callback,
        )
    }
}
