// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberCommandArgs {
    pub version: u32,
    pub ticket_id: String,
    pub backend_id: String,
    pub command_id: String,
    pub operation: String,
    pub context_revision: String,
    pub issued_at: String,
    pub payload_json: String,
}

impl From<TicketremoteMemberCommandArgs> for super::Reducer {
    fn from(args: TicketremoteMemberCommandArgs) -> Self {
        Self::TicketremoteMemberCommand {
            version: args.version,
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            command_id: args.command_id,
            operation: args.operation,
            context_revision: args.context_revision,
            issued_at: args.issued_at,
            payload_json: args.payload_json,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberCommandArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_command {
    /// Request that the remote module invoke the reducer `ticketremote_member_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_command:ticketremote_member_command_then`] to run a callback after the reducer completes.
    fn ticketremote_member_command(
        &self,
        version: u32,
        ticket_id: String,
        backend_id: String,
        command_id: String,
        operation: String,
        context_revision: String,
        issued_at: String,
        payload_json: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_command_then(
            version,
            ticket_id,
            backend_id,
            command_id,
            operation,
            context_revision,
            issued_at,
            payload_json,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_command` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_command_then(
        &self,
        version: u32,
        ticket_id: String,
        backend_id: String,
        command_id: String,
        operation: String,
        context_revision: String,
        issued_at: String,
        payload_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_command for super::RemoteReducers {
    fn ticketremote_member_command_then(
        &self,
        version: u32,
        ticket_id: String,
        backend_id: String,
        command_id: String,
        operation: String,
        context_revision: String,
        issued_at: String,
        payload_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberCommandArgs {
                version,
                ticket_id,
                backend_id,
                command_id,
                operation,
                context_revision,
                issued_at,
                payload_json,
            },
            callback,
        )
    }
}
