// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberCloseControlCodeArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub session_id: String,
    pub request_id: String,
    pub reason: String,
}

impl From<TicketremoteMemberCloseControlCodeArgs> for super::Reducer {
    fn from(args: TicketremoteMemberCloseControlCodeArgs) -> Self {
        Self::TicketremoteMemberCloseControlCode {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            session_id: args.session_id,
            request_id: args.request_id,
            reason: args.reason,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberCloseControlCodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_close_control_code`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_close_control_code {
    /// Request that the remote module invoke the reducer `ticketremote_member_close_control_code` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_close_control_code:ticketremote_member_close_control_code_then`] to run a callback after the reducer completes.
    fn ticketremote_member_close_control_code(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        request_id: String,
        reason: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_close_control_code_then(
            ticket_id,
            backend_id,
            session_id,
            request_id,
            reason,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_close_control_code` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_close_control_code_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        request_id: String,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_close_control_code for super::RemoteReducers {
    fn ticketremote_member_close_control_code_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        request_id: String,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberCloseControlCodeArgs {
                ticket_id,
                backend_id,
                session_id,
                request_id,
                reason,
            },
            callback,
        )
    }
}
