// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteUpdatePhoneCurrentReportArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub stream_state: String,
    pub desired_active: bool,
    pub last_command_id: String,
    pub last_command_revision: String,
    pub status_json: String,
    pub now_arg: String,
}

impl From<TicketremoteUpdatePhoneCurrentReportArgs> for super::Reducer {
    fn from(args: TicketremoteUpdatePhoneCurrentReportArgs) -> Self {
        Self::TicketremoteUpdatePhoneCurrentReport {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            stream_state: args.stream_state,
            desired_active: args.desired_active,
            last_command_id: args.last_command_id,
            last_command_revision: args.last_command_revision,
            status_json: args.status_json,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteUpdatePhoneCurrentReportArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_update_phone_current_report`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_update_phone_current_report {
    /// Request that the remote module invoke the reducer `ticketremote_update_phone_current_report` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_update_phone_current_report:ticketremote_update_phone_current_report_then`] to run a callback after the reducer completes.
    fn ticketremote_update_phone_current_report(
        &self,
        ticket_id: String,
        backend_id: String,
        stream_state: String,
        desired_active: bool,
        last_command_id: String,
        last_command_revision: String,
        status_json: String,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_update_phone_current_report_then(
            ticket_id,
            backend_id,
            stream_state,
            desired_active,
            last_command_id,
            last_command_revision,
            status_json,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_update_phone_current_report` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_update_phone_current_report_then(
        &self,
        ticket_id: String,
        backend_id: String,
        stream_state: String,
        desired_active: bool,
        last_command_id: String,
        last_command_revision: String,
        status_json: String,
        now_arg: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_update_phone_current_report for super::RemoteReducers {
    fn ticketremote_update_phone_current_report_then(
        &self,
        ticket_id: String,
        backend_id: String,
        stream_state: String,
        desired_active: bool,
        last_command_id: String,
        last_command_revision: String,
        status_json: String,
        now_arg: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteUpdatePhoneCurrentReportArgs {
                ticket_id,
                backend_id,
                stream_state,
                desired_active,
                last_command_id,
                last_command_revision,
                status_json,
                now_arg,
            },
            callback,
        )
    }
}
