// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteDevPerfMetric {
    pub id: String,
    pub ticket_id: String,
    pub source: String,
    pub metric_name: String,
    pub phase: String,
    pub flow_id: String,
    pub value_millis: u32,
    pub ok: bool,
    pub detail_json: String,
    pub created_at: String,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteDevPerfMetric {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteDevPerfMetric`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteDevPerfMetricCols {
    pub id: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, String>,
    pub source: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, String>,
    pub metric_name: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, String>,
    pub phase: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, String>,
    pub flow_id: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, String>,
    pub value_millis: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, u32>,
    pub ok: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, bool>,
    pub detail_json: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, String>,
    pub created_at: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteDevPerfMetric, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteDevPerfMetric {
    type Cols = TicketremoteDevPerfMetricCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteDevPerfMetricCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            metric_name: __sdk::__query_builder::Col::new(table_name, "metric_name"),
            phase: __sdk::__query_builder::Col::new(table_name, "phase"),
            flow_id: __sdk::__query_builder::Col::new(table_name, "flow_id"),
            value_millis: __sdk::__query_builder::Col::new(table_name, "value_millis"),
            ok: __sdk::__query_builder::Col::new(table_name, "ok"),
            detail_json: __sdk::__query_builder::Col::new(table_name, "detail_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteDevPerfMetric`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteDevPerfMetricIxCols {
    pub created_at: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetric, String>,
    pub expires_at: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetric, String>,
    pub flow_id: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetric, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetric, String>,
    pub metric_name: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetric, String>,
    pub phase: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetric, String>,
    pub source: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetric, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetric, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteDevPerfMetric {
    type IxCols = TicketremoteDevPerfMetricIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteDevPerfMetricIxCols {
            created_at: __sdk::__query_builder::IxCol::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            flow_id: __sdk::__query_builder::IxCol::new(table_name, "flow_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            metric_name: __sdk::__query_builder::IxCol::new(table_name, "metric_name"),
            phase: __sdk::__query_builder::IxCol::new(table_name, "phase"),
            source: __sdk::__query_builder::IxCol::new(table_name, "source"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteDevPerfMetric {}
