// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_service_ticket_type::TicketremoteServiceTicket;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_service_ticket`.
///
/// Obtain a handle from the [`TicketremoteServiceTicketTableAccess::ticketremote_service_ticket`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_service_ticket()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_ticket().on_insert(...)`.
pub struct TicketremoteServiceTicketTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteServiceTicket>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_service_ticket`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteServiceTicketTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteServiceTicketTableHandle`], which mediates access to the table `ticketremote_service_ticket`.
    fn ticketremote_service_ticket(&self) -> TicketremoteServiceTicketTableHandle<'_>;
}

impl TicketremoteServiceTicketTableAccess for super::RemoteTables {
    fn ticketremote_service_ticket(&self) -> TicketremoteServiceTicketTableHandle<'_> {
        TicketremoteServiceTicketTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteServiceTicket>("ticketremote_service_ticket"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteServiceTicketInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteServiceTicketDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteServiceTicketTableHandle<'ctx> {
    type Row = TicketremoteServiceTicket;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteServiceTicket> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteServiceTicketInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceTicketInsertCallbackId {
        TicketremoteServiceTicketInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteServiceTicketInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteServiceTicketDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceTicketDeleteCallbackId {
        TicketremoteServiceTicketDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteServiceTicketDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteServiceTicketUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteServiceTicketTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteServiceTicketUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceTicketUpdateCallbackId {
        TicketremoteServiceTicketUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteServiceTicketUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_service_ticket`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteServiceTicketIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_ticket().id().find(...)`.
pub struct TicketremoteServiceTicketIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteServiceTicket, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteServiceTicketTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_service_ticket`.
    pub fn id(&self) -> TicketremoteServiceTicketIdUnique<'ctx> {
        TicketremoteServiceTicketIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteServiceTicketIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteServiceTicket> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<TicketremoteServiceTicket>("ticketremote_service_ticket");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteServiceTicket>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TicketremoteServiceTicket>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteServiceTicket`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_service_ticketQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteServiceTicket`.
    fn ticketremote_service_ticket(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceTicket>;
}

impl ticketremote_service_ticketQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_service_ticket(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceTicket> {
        __sdk::__query_builder::Table::new("ticketremote_service_ticket")
    }
}
