// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteTicketSliderRegionV3 {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub proof_action_id: String,
    pub stream_epoch: String,
    pub frame_sequence: String,
    pub left_basis_points: u32,
    pub top_basis_points: u32,
    pub right_basis_points: u32,
    pub bottom_basis_points: u32,
    pub updated_at: String,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteTicketSliderRegionV3 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteTicketSliderRegionV3`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteTicketSliderRegionV3Cols {
    pub id: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, String>,
    pub proof_action_id: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, String>,
    pub stream_epoch: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, String>,
    pub frame_sequence: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, String>,
    pub left_basis_points: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, u32>,
    pub top_basis_points: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, u32>,
    pub right_basis_points: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, u32>,
    pub bottom_basis_points: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, u32>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteTicketSliderRegionV3, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteTicketSliderRegionV3 {
    type Cols = TicketremoteTicketSliderRegionV3Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteTicketSliderRegionV3Cols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            proof_action_id: __sdk::__query_builder::Col::new(table_name, "proof_action_id"),
            stream_epoch: __sdk::__query_builder::Col::new(table_name, "stream_epoch"),
            frame_sequence: __sdk::__query_builder::Col::new(table_name, "frame_sequence"),
            left_basis_points: __sdk::__query_builder::Col::new(table_name, "left_basis_points"),
            top_basis_points: __sdk::__query_builder::Col::new(table_name, "top_basis_points"),
            right_basis_points: __sdk::__query_builder::Col::new(table_name, "right_basis_points"),
            bottom_basis_points: __sdk::__query_builder::Col::new(
                table_name,
                "bottom_basis_points",
            ),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteTicketSliderRegionV3`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteTicketSliderRegionV3IxCols {
    pub backend_id: __sdk::__query_builder::IxCol<TicketremoteTicketSliderRegionV3, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteTicketSliderRegionV3, String>,
    pub proof_action_id: __sdk::__query_builder::IxCol<TicketremoteTicketSliderRegionV3, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteTicketSliderRegionV3, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteTicketSliderRegionV3 {
    type IxCols = TicketremoteTicketSliderRegionV3IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteTicketSliderRegionV3IxCols {
            backend_id: __sdk::__query_builder::IxCol::new(table_name, "backend_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            proof_action_id: __sdk::__query_builder::IxCol::new(table_name, "proof_action_id"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteTicketSliderRegionV3 {}
