// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteMemberHdrBoostState {
    pub id: String,
    pub ticket_id: String,
    pub account_scope_id: String,
    pub selected_display_boost: u32,
    pub updated_at: String,
    pub server_at: String,
}

impl __sdk::InModule for TicketremoteMemberHdrBoostState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteMemberHdrBoostState`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteMemberHdrBoostStateCols {
    pub id: __sdk::__query_builder::Col<TicketremoteMemberHdrBoostState, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteMemberHdrBoostState, String>,
    pub account_scope_id: __sdk::__query_builder::Col<TicketremoteMemberHdrBoostState, String>,
    pub selected_display_boost: __sdk::__query_builder::Col<TicketremoteMemberHdrBoostState, u32>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteMemberHdrBoostState, String>,
    pub server_at: __sdk::__query_builder::Col<TicketremoteMemberHdrBoostState, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteMemberHdrBoostState {
    type Cols = TicketremoteMemberHdrBoostStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteMemberHdrBoostStateCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            account_scope_id: __sdk::__query_builder::Col::new(table_name, "account_scope_id"),
            selected_display_boost: __sdk::__query_builder::Col::new(
                table_name,
                "selected_display_boost",
            ),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            server_at: __sdk::__query_builder::Col::new(table_name, "server_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteMemberHdrBoostState`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteMemberHdrBoostStateIxCols {
    pub account_scope_id: __sdk::__query_builder::IxCol<TicketremoteMemberHdrBoostState, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteMemberHdrBoostState, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteMemberHdrBoostState, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteMemberHdrBoostState {
    type IxCols = TicketremoteMemberHdrBoostStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteMemberHdrBoostStateIxCols {
            account_scope_id: __sdk::__query_builder::IxCol::new(table_name, "account_scope_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteMemberHdrBoostState {}
