// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_member_stream_state_type::TicketremoteMemberStreamState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_member_stream_state`.
///
/// Obtain a handle from the [`TicketremoteMemberStreamStateTableAccess::ticketremote_member_stream_state`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_member_stream_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_member_stream_state().on_insert(...)`.
pub struct TicketremoteMemberStreamStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteMemberStreamState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_member_stream_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteMemberStreamStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteMemberStreamStateTableHandle`], which mediates access to the table `ticketremote_member_stream_state`.
    fn ticketremote_member_stream_state(&self) -> TicketremoteMemberStreamStateTableHandle<'_>;
}

impl TicketremoteMemberStreamStateTableAccess for super::RemoteTables {
    fn ticketremote_member_stream_state(&self) -> TicketremoteMemberStreamStateTableHandle<'_> {
        TicketremoteMemberStreamStateTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteMemberStreamState>("ticketremote_member_stream_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteMemberStreamStateInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteMemberStreamStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteMemberStreamStateTableHandle<'ctx> {
    type Row = TicketremoteMemberStreamState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteMemberStreamState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteMemberStreamStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberStreamStateInsertCallbackId {
        TicketremoteMemberStreamStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteMemberStreamStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteMemberStreamStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberStreamStateDeleteCallbackId {
        TicketremoteMemberStreamStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteMemberStreamStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteMemberStreamStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteMemberStreamStateTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteMemberStreamStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberStreamStateUpdateCallbackId {
        TicketremoteMemberStreamStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteMemberStreamStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_member_stream_state`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteMemberStreamStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_member_stream_state().id().find(...)`.
pub struct TicketremoteMemberStreamStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteMemberStreamState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteMemberStreamStateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_member_stream_state`.
    pub fn id(&self) -> TicketremoteMemberStreamStateIdUnique<'ctx> {
        TicketremoteMemberStreamStateIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteMemberStreamStateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteMemberStreamState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremoteMemberStreamState>("ticketremote_member_stream_state");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteMemberStreamState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteMemberStreamState>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteMemberStreamState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_member_stream_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteMemberStreamState`.
    fn ticketremote_member_stream_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteMemberStreamState>;
}

impl ticketremote_member_stream_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_member_stream_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteMemberStreamState> {
        __sdk::__query_builder::Table::new("ticketremote_member_stream_state")
    }
}
