// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteStreamDesiredState {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub desired_active: bool,
    pub viewer_count: u32,
    pub reason: String,
    pub revision: String,
    pub updated_by: String,
    pub updated_at: String,
}

impl __sdk::InModule for TicketremoteStreamDesiredState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteStreamDesiredState`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteStreamDesiredStateCols {
    pub id: __sdk::__query_builder::Col<TicketremoteStreamDesiredState, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteStreamDesiredState, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteStreamDesiredState, String>,
    pub desired_active: __sdk::__query_builder::Col<TicketremoteStreamDesiredState, bool>,
    pub viewer_count: __sdk::__query_builder::Col<TicketremoteStreamDesiredState, u32>,
    pub reason: __sdk::__query_builder::Col<TicketremoteStreamDesiredState, String>,
    pub revision: __sdk::__query_builder::Col<TicketremoteStreamDesiredState, String>,
    pub updated_by: __sdk::__query_builder::Col<TicketremoteStreamDesiredState, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteStreamDesiredState, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteStreamDesiredState {
    type Cols = TicketremoteStreamDesiredStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteStreamDesiredStateCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            desired_active: __sdk::__query_builder::Col::new(table_name, "desired_active"),
            viewer_count: __sdk::__query_builder::Col::new(table_name, "viewer_count"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            updated_by: __sdk::__query_builder::Col::new(table_name, "updated_by"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteStreamDesiredState`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteStreamDesiredStateIxCols {
    pub id: __sdk::__query_builder::IxCol<TicketremoteStreamDesiredState, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteStreamDesiredState {
    type IxCols = TicketremoteStreamDesiredStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteStreamDesiredStateIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteStreamDesiredState {}
