// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteDevPerfMetricsConfig {
    pub ticket_id: String,
    pub enabled: bool,
    pub reason: String,
    pub expires_at: String,
    pub updated_at: String,
}

impl __sdk::InModule for TicketremoteDevPerfMetricsConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteDevPerfMetricsConfig`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteDevPerfMetricsConfigCols {
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteDevPerfMetricsConfig, String>,
    pub enabled: __sdk::__query_builder::Col<TicketremoteDevPerfMetricsConfig, bool>,
    pub reason: __sdk::__query_builder::Col<TicketremoteDevPerfMetricsConfig, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteDevPerfMetricsConfig, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteDevPerfMetricsConfig, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteDevPerfMetricsConfig {
    type Cols = TicketremoteDevPerfMetricsConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteDevPerfMetricsConfigCols {
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            enabled: __sdk::__query_builder::Col::new(table_name, "enabled"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteDevPerfMetricsConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteDevPerfMetricsConfigIxCols {
    pub expires_at: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetricsConfig, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetricsConfig, String>,
    pub updated_at: __sdk::__query_builder::IxCol<TicketremoteDevPerfMetricsConfig, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteDevPerfMetricsConfig {
    type IxCols = TicketremoteDevPerfMetricsConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteDevPerfMetricsConfigIxCols {
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
            updated_at: __sdk::__query_builder::IxCol::new(table_name, "updated_at"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteDevPerfMetricsConfig {}
