// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteCancelLatestTicketReselectArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub schedule_id: String,
    pub now_arg: String,
}

impl From<TicketremoteCancelLatestTicketReselectArgs> for super::Reducer {
    fn from(args: TicketremoteCancelLatestTicketReselectArgs) -> Self {
        Self::TicketremoteCancelLatestTicketReselect {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            schedule_id: args.schedule_id,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteCancelLatestTicketReselectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_cancel_latest_ticket_reselect`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_cancel_latest_ticket_reselect {
    /// Request that the remote module invoke the reducer `ticketremote_cancel_latest_ticket_reselect` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_cancel_latest_ticket_reselect:ticketremote_cancel_latest_ticket_reselect_then`] to run a callback after the reducer completes.
    fn ticketremote_cancel_latest_ticket_reselect(
        &self,
        ticket_id: String,
        backend_id: String,
        schedule_id: String,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_cancel_latest_ticket_reselect_then(
            ticket_id,
            backend_id,
            schedule_id,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_cancel_latest_ticket_reselect` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_cancel_latest_ticket_reselect_then(
        &self,
        ticket_id: String,
        backend_id: String,
        schedule_id: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_cancel_latest_ticket_reselect for super::RemoteReducers {
    fn ticketremote_cancel_latest_ticket_reselect_then(
        &self,
        ticket_id: String,
        backend_id: String,
        schedule_id: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteCancelLatestTicketReselectArgs {
                ticket_id,
                backend_id,
                schedule_id,
                now_arg,
            },
            callback,
        )
    }
}
