// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_ticket_summary_type::TicketremoteTicketSummary;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_ticket_summary`.
///
/// Obtain a handle from the [`TicketremoteTicketSummaryTableAccess::ticketremote_ticket_summary`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_ticket_summary()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_ticket_summary().on_insert(...)`.
pub struct TicketremoteTicketSummaryTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteTicketSummary>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_ticket_summary`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteTicketSummaryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteTicketSummaryTableHandle`], which mediates access to the table `ticketremote_ticket_summary`.
    fn ticketremote_ticket_summary(&self) -> TicketremoteTicketSummaryTableHandle<'_>;
}

impl TicketremoteTicketSummaryTableAccess for super::RemoteTables {
    fn ticketremote_ticket_summary(&self) -> TicketremoteTicketSummaryTableHandle<'_> {
        TicketremoteTicketSummaryTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteTicketSummary>("ticketremote_ticket_summary"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteTicketSummaryInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteTicketSummaryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteTicketSummaryTableHandle<'ctx> {
    type Row = TicketremoteTicketSummary;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteTicketSummary> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteTicketSummaryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteTicketSummaryInsertCallbackId {
        TicketremoteTicketSummaryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteTicketSummaryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteTicketSummaryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteTicketSummaryDeleteCallbackId {
        TicketremoteTicketSummaryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteTicketSummaryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteTicketSummaryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteTicketSummaryTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteTicketSummaryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteTicketSummaryUpdateCallbackId {
        TicketremoteTicketSummaryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteTicketSummaryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_ticket_summary`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteTicketSummaryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_ticket_summary().id().find(...)`.
pub struct TicketremoteTicketSummaryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteTicketSummary, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteTicketSummaryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_ticket_summary`.
    pub fn id(&self) -> TicketremoteTicketSummaryIdUnique<'ctx> {
        TicketremoteTicketSummaryIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteTicketSummaryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteTicketSummary> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<TicketremoteTicketSummary>("ticketremote_ticket_summary");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteTicketSummary>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TicketremoteTicketSummary>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteTicketSummary`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_ticket_summaryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteTicketSummary`.
    fn ticketremote_ticket_summary(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteTicketSummary>;
}

impl ticketremote_ticket_summaryQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_ticket_summary(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteTicketSummary> {
        __sdk::__query_builder::Table::new("ticketremote_ticket_summary")
    }
}
