// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_invitation_type::TicketremoteInvitation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_service_invitation`.
///
/// Obtain a handle from the [`TicketremoteServiceInvitationTableAccess::ticketremote_service_invitation`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_service_invitation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_invitation().on_insert(...)`.
pub struct TicketremoteServiceInvitationTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteInvitation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_service_invitation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteServiceInvitationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteServiceInvitationTableHandle`], which mediates access to the table `ticketremote_service_invitation`.
    fn ticketremote_service_invitation(&self) -> TicketremoteServiceInvitationTableHandle<'_>;
}

impl TicketremoteServiceInvitationTableAccess for super::RemoteTables {
    fn ticketremote_service_invitation(&self) -> TicketremoteServiceInvitationTableHandle<'_> {
        TicketremoteServiceInvitationTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteInvitation>("ticketremote_service_invitation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteServiceInvitationInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteServiceInvitationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteServiceInvitationTableHandle<'ctx> {
    type Row = TicketremoteInvitation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteInvitation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteServiceInvitationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceInvitationInsertCallbackId {
        TicketremoteServiceInvitationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteServiceInvitationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteServiceInvitationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceInvitationDeleteCallbackId {
        TicketremoteServiceInvitationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteServiceInvitationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteServiceInvitationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteServiceInvitationTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteServiceInvitationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceInvitationUpdateCallbackId {
        TicketremoteServiceInvitationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteServiceInvitationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_service_invitation`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteServiceInvitationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_invitation().id().find(...)`.
pub struct TicketremoteServiceInvitationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteInvitation, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteServiceInvitationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_service_invitation`.
    pub fn id(&self) -> TicketremoteServiceInvitationIdUnique<'ctx> {
        TicketremoteServiceInvitationIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteServiceInvitationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteInvitation> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<TicketremoteInvitation>("ticketremote_service_invitation");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteInvitation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TicketremoteInvitation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteInvitation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_service_invitationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteInvitation`.
    fn ticketremote_service_invitation(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteInvitation>;
}

impl ticketremote_service_invitationQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_service_invitation(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteInvitation> {
        __sdk::__query_builder::Table::new("ticketremote_service_invitation")
    }
}
