// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremotePurgeSensitiveOperationalLogsArgs {
    pub ticket_id: String,
}

impl From<TicketremotePurgeSensitiveOperationalLogsArgs> for super::Reducer {
    fn from(args: TicketremotePurgeSensitiveOperationalLogsArgs) -> Self {
        Self::TicketremotePurgeSensitiveOperationalLogs {
            ticket_id: args.ticket_id,
        }
    }
}

impl __sdk::InModule for TicketremotePurgeSensitiveOperationalLogsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_purge_sensitive_operational_logs`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_purge_sensitive_operational_logs {
    /// Request that the remote module invoke the reducer `ticketremote_purge_sensitive_operational_logs` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_purge_sensitive_operational_logs:ticketremote_purge_sensitive_operational_logs_then`] to run a callback after the reducer completes.
    fn ticketremote_purge_sensitive_operational_logs(
        &self,
        ticket_id: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_purge_sensitive_operational_logs_then(ticket_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ticketremote_purge_sensitive_operational_logs` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_purge_sensitive_operational_logs_then(
        &self,
        ticket_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_purge_sensitive_operational_logs for super::RemoteReducers {
    fn ticketremote_purge_sensitive_operational_logs_then(
        &self,
        ticket_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremotePurgeSensitiveOperationalLogsArgs { ticket_id },
            callback,
        )
    }
}
