// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_service_control_type::TicketremoteServiceControl;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_service_control_session`.
///
/// Obtain a handle from the [`TicketremoteServiceControlSessionTableAccess::ticketremote_service_control_session`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_service_control_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_control_session().on_insert(...)`.
pub struct TicketremoteServiceControlSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteServiceControl>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_service_control_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteServiceControlSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteServiceControlSessionTableHandle`], which mediates access to the table `ticketremote_service_control_session`.
    fn ticketremote_service_control_session(
        &self,
    ) -> TicketremoteServiceControlSessionTableHandle<'_>;
}

impl TicketremoteServiceControlSessionTableAccess for super::RemoteTables {
    fn ticketremote_service_control_session(
        &self,
    ) -> TicketremoteServiceControlSessionTableHandle<'_> {
        TicketremoteServiceControlSessionTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteServiceControl>("ticketremote_service_control_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteServiceControlSessionInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteServiceControlSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteServiceControlSessionTableHandle<'ctx> {
    type Row = TicketremoteServiceControl;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteServiceControl> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteServiceControlSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceControlSessionInsertCallbackId {
        TicketremoteServiceControlSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteServiceControlSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteServiceControlSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceControlSessionDeleteCallbackId {
        TicketremoteServiceControlSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteServiceControlSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteServiceControlSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteServiceControlSessionTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteServiceControlSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceControlSessionUpdateCallbackId {
        TicketremoteServiceControlSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteServiceControlSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_service_control_session`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteServiceControlSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_control_session().id().find(...)`.
pub struct TicketremoteServiceControlSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteServiceControl, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteServiceControlSessionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_service_control_session`.
    pub fn id(&self) -> TicketremoteServiceControlSessionIdUnique<'ctx> {
        TicketremoteServiceControlSessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteServiceControlSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteServiceControl> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremoteServiceControl>("ticketremote_service_control_session");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteServiceControl>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TicketremoteServiceControl>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteServiceControl`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_service_control_sessionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteServiceControl`.
    fn ticketremote_service_control_session(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceControl>;
}

impl ticketremote_service_control_sessionQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_service_control_session(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceControl> {
        __sdk::__query_builder::Table::new("ticketremote_service_control_session")
    }
}
