// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteUpdateControlCodeFastStateArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub status: String,
    pub revision: String,
    pub reason: String,
    pub stream_epoch: String,
    pub frame_sequence: String,
    pub raw_ticket_confirmed: bool,
    pub cleanup_clear: bool,
    pub stream_live: bool,
    pub now_arg: String,
}

impl From<TicketremoteUpdateControlCodeFastStateArgs> for super::Reducer {
    fn from(args: TicketremoteUpdateControlCodeFastStateArgs) -> Self {
        Self::TicketremoteUpdateControlCodeFastState {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            status: args.status,
            revision: args.revision,
            reason: args.reason,
            stream_epoch: args.stream_epoch,
            frame_sequence: args.frame_sequence,
            raw_ticket_confirmed: args.raw_ticket_confirmed,
            cleanup_clear: args.cleanup_clear,
            stream_live: args.stream_live,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteUpdateControlCodeFastStateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_update_control_code_fast_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_update_control_code_fast_state {
    /// Request that the remote module invoke the reducer `ticketremote_update_control_code_fast_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_update_control_code_fast_state:ticketremote_update_control_code_fast_state_then`] to run a callback after the reducer completes.
    fn ticketremote_update_control_code_fast_state(
        &self,
        ticket_id: String,
        backend_id: String,
        status: String,
        revision: String,
        reason: String,
        stream_epoch: String,
        frame_sequence: String,
        raw_ticket_confirmed: bool,
        cleanup_clear: bool,
        stream_live: bool,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_update_control_code_fast_state_then(
            ticket_id,
            backend_id,
            status,
            revision,
            reason,
            stream_epoch,
            frame_sequence,
            raw_ticket_confirmed,
            cleanup_clear,
            stream_live,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_update_control_code_fast_state` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_update_control_code_fast_state_then(
        &self,
        ticket_id: String,
        backend_id: String,
        status: String,
        revision: String,
        reason: String,
        stream_epoch: String,
        frame_sequence: String,
        raw_ticket_confirmed: bool,
        cleanup_clear: bool,
        stream_live: bool,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_update_control_code_fast_state for super::RemoteReducers {
    fn ticketremote_update_control_code_fast_state_then(
        &self,
        ticket_id: String,
        backend_id: String,
        status: String,
        revision: String,
        reason: String,
        stream_epoch: String,
        frame_sequence: String,
        raw_ticket_confirmed: bool,
        cleanup_clear: bool,
        stream_live: bool,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteUpdateControlCodeFastStateArgs {
                ticket_id,
                backend_id,
                status,
                revision,
                reason,
                stream_epoch,
                frame_sequence,
                raw_ticket_confirmed,
                cleanup_clear,
                stream_live,
                now_arg,
            },
            callback,
        )
    }
}
