// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberRequestControlCodeArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub session_id: String,
    pub digits: String,
}

impl From<TicketremoteMemberRequestControlCodeArgs> for super::Reducer {
    fn from(args: TicketremoteMemberRequestControlCodeArgs) -> Self {
        Self::TicketremoteMemberRequestControlCode {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            session_id: args.session_id,
            digits: args.digits,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberRequestControlCodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_request_control_code`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_request_control_code {
    /// Request that the remote module invoke the reducer `ticketremote_member_request_control_code` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_request_control_code:ticketremote_member_request_control_code_then`] to run a callback after the reducer completes.
    fn ticketremote_member_request_control_code(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        digits: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_request_control_code_then(
            ticket_id,
            backend_id,
            session_id,
            digits,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_request_control_code` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_request_control_code_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        digits: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_request_control_code for super::RemoteReducers {
    fn ticketremote_member_request_control_code_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        digits: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberRequestControlCodeArgs {
                ticket_id,
                backend_id,
                session_id,
                digits,
            },
            callback,
        )
    }
}
