// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_viewer_public_type::TicketremoteViewerPublic;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_viewer_public`.
///
/// Obtain a handle from the [`TicketremoteViewerPublicTableAccess::ticketremote_viewer_public`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_viewer_public()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_viewer_public().on_insert(...)`.
pub struct TicketremoteViewerPublicTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteViewerPublic>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_viewer_public`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteViewerPublicTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteViewerPublicTableHandle`], which mediates access to the table `ticketremote_viewer_public`.
    fn ticketremote_viewer_public(&self) -> TicketremoteViewerPublicTableHandle<'_>;
}

impl TicketremoteViewerPublicTableAccess for super::RemoteTables {
    fn ticketremote_viewer_public(&self) -> TicketremoteViewerPublicTableHandle<'_> {
        TicketremoteViewerPublicTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteViewerPublic>("ticketremote_viewer_public"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteViewerPublicInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteViewerPublicDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteViewerPublicTableHandle<'ctx> {
    type Row = TicketremoteViewerPublic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteViewerPublic> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteViewerPublicInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteViewerPublicInsertCallbackId {
        TicketremoteViewerPublicInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteViewerPublicInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteViewerPublicDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteViewerPublicDeleteCallbackId {
        TicketremoteViewerPublicDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteViewerPublicDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteViewerPublicUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteViewerPublicTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteViewerPublicUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteViewerPublicUpdateCallbackId {
        TicketremoteViewerPublicUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteViewerPublicUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_viewer_public`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteViewerPublicIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_viewer_public().id().find(...)`.
pub struct TicketremoteViewerPublicIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteViewerPublic, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteViewerPublicTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_viewer_public`.
    pub fn id(&self) -> TicketremoteViewerPublicIdUnique<'ctx> {
        TicketremoteViewerPublicIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteViewerPublicIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteViewerPublic> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<TicketremoteViewerPublic>("ticketremote_viewer_public");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteViewerPublic>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TicketremoteViewerPublic>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteViewerPublic`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_viewer_publicQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteViewerPublic`.
    fn ticketremote_viewer_public(&self)
    -> __sdk::__query_builder::Table<TicketremoteViewerPublic>;
}

impl ticketremote_viewer_publicQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_viewer_public(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteViewerPublic> {
        __sdk::__query_builder::Table::new("ticketremote_viewer_public")
    }
}
