// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_phone_control_state_type::TicketremotePhoneControlState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_phone_control_state`.
///
/// Obtain a handle from the [`TicketremotePhoneControlStateTableAccess::ticketremote_phone_control_state`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_phone_control_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_phone_control_state().on_insert(...)`.
pub struct TicketremotePhoneControlStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremotePhoneControlState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_phone_control_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremotePhoneControlStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremotePhoneControlStateTableHandle`], which mediates access to the table `ticketremote_phone_control_state`.
    fn ticketremote_phone_control_state(&self) -> TicketremotePhoneControlStateTableHandle<'_>;
}

impl TicketremotePhoneControlStateTableAccess for super::RemoteTables {
    fn ticketremote_phone_control_state(&self) -> TicketremotePhoneControlStateTableHandle<'_> {
        TicketremotePhoneControlStateTableHandle {
            imp: self
                .imp
                .get_table::<TicketremotePhoneControlState>("ticketremote_phone_control_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremotePhoneControlStateInsertCallbackId(__sdk::CallbackId);
pub struct TicketremotePhoneControlStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremotePhoneControlStateTableHandle<'ctx> {
    type Row = TicketremotePhoneControlState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremotePhoneControlState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremotePhoneControlStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremotePhoneControlStateInsertCallbackId {
        TicketremotePhoneControlStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremotePhoneControlStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremotePhoneControlStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremotePhoneControlStateDeleteCallbackId {
        TicketremotePhoneControlStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremotePhoneControlStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremotePhoneControlStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremotePhoneControlStateTableHandle<'ctx> {
    type UpdateCallbackId = TicketremotePhoneControlStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremotePhoneControlStateUpdateCallbackId {
        TicketremotePhoneControlStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremotePhoneControlStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_phone_control_state`,
/// which allows point queries on the field of the same name
/// via the [`TicketremotePhoneControlStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_phone_control_state().id().find(...)`.
pub struct TicketremotePhoneControlStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremotePhoneControlState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremotePhoneControlStateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_phone_control_state`.
    pub fn id(&self) -> TicketremotePhoneControlStateIdUnique<'ctx> {
        TicketremotePhoneControlStateIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremotePhoneControlStateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremotePhoneControlState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremotePhoneControlState>("ticketremote_phone_control_state");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremotePhoneControlState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremotePhoneControlState>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremotePhoneControlState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_phone_control_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremotePhoneControlState`.
    fn ticketremote_phone_control_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremotePhoneControlState>;
}

impl ticketremote_phone_control_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_phone_control_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremotePhoneControlState> {
        __sdk::__query_builder::Table::new("ticketremote_phone_control_state")
    }
}
