// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteServiceViewer {
    pub session_id: String,
    pub ticket_id: String,
    pub email: String,
    pub display_name: String,
    pub page: String,
    pub connected: bool,
    pub last_seen_at: String,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteServiceViewer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteServiceViewer`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteServiceViewerCols {
    pub session_id: __sdk::__query_builder::Col<TicketremoteServiceViewer, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteServiceViewer, String>,
    pub email: __sdk::__query_builder::Col<TicketremoteServiceViewer, String>,
    pub display_name: __sdk::__query_builder::Col<TicketremoteServiceViewer, String>,
    pub page: __sdk::__query_builder::Col<TicketremoteServiceViewer, String>,
    pub connected: __sdk::__query_builder::Col<TicketremoteServiceViewer, bool>,
    pub last_seen_at: __sdk::__query_builder::Col<TicketremoteServiceViewer, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteServiceViewer, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteServiceViewer {
    type Cols = TicketremoteServiceViewerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteServiceViewerCols {
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            page: __sdk::__query_builder::Col::new(table_name, "page"),
            connected: __sdk::__query_builder::Col::new(table_name, "connected"),
            last_seen_at: __sdk::__query_builder::Col::new(table_name, "last_seen_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}
