// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteServiceMemberAccount {
    pub id: String,
    pub ticket_id: String,
    pub email: String,
    pub public_id: String,
    pub account_scope_id: String,
    pub role: String,
    pub active: bool,
    pub updated_at: String,
}

impl __sdk::InModule for TicketremoteServiceMemberAccount {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteServiceMemberAccount`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteServiceMemberAccountCols {
    pub id: __sdk::__query_builder::Col<TicketremoteServiceMemberAccount, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteServiceMemberAccount, String>,
    pub email: __sdk::__query_builder::Col<TicketremoteServiceMemberAccount, String>,
    pub public_id: __sdk::__query_builder::Col<TicketremoteServiceMemberAccount, String>,
    pub account_scope_id: __sdk::__query_builder::Col<TicketremoteServiceMemberAccount, String>,
    pub role: __sdk::__query_builder::Col<TicketremoteServiceMemberAccount, String>,
    pub active: __sdk::__query_builder::Col<TicketremoteServiceMemberAccount, bool>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteServiceMemberAccount, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteServiceMemberAccount {
    type Cols = TicketremoteServiceMemberAccountCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteServiceMemberAccountCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            public_id: __sdk::__query_builder::Col::new(table_name, "public_id"),
            account_scope_id: __sdk::__query_builder::Col::new(table_name, "account_scope_id"),
            role: __sdk::__query_builder::Col::new(table_name, "role"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}
