// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_member_hdr_engine_state_type::TicketremoteMemberHdrEngineState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_member_hdr_engine_state`.
///
/// Obtain a handle from the [`TicketremoteMemberHdrEngineStateTableAccess::ticketremote_member_hdr_engine_state`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_member_hdr_engine_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_member_hdr_engine_state().on_insert(...)`.
pub struct TicketremoteMemberHdrEngineStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteMemberHdrEngineState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_member_hdr_engine_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteMemberHdrEngineStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteMemberHdrEngineStateTableHandle`], which mediates access to the table `ticketremote_member_hdr_engine_state`.
    fn ticketremote_member_hdr_engine_state(
        &self,
    ) -> TicketremoteMemberHdrEngineStateTableHandle<'_>;
}

impl TicketremoteMemberHdrEngineStateTableAccess for super::RemoteTables {
    fn ticketremote_member_hdr_engine_state(
        &self,
    ) -> TicketremoteMemberHdrEngineStateTableHandle<'_> {
        TicketremoteMemberHdrEngineStateTableHandle {
            imp: self.imp.get_table::<TicketremoteMemberHdrEngineState>(
                "ticketremote_member_hdr_engine_state",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteMemberHdrEngineStateInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteMemberHdrEngineStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteMemberHdrEngineStateTableHandle<'ctx> {
    type Row = TicketremoteMemberHdrEngineState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteMemberHdrEngineState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteMemberHdrEngineStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberHdrEngineStateInsertCallbackId {
        TicketremoteMemberHdrEngineStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteMemberHdrEngineStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteMemberHdrEngineStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberHdrEngineStateDeleteCallbackId {
        TicketremoteMemberHdrEngineStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteMemberHdrEngineStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteMemberHdrEngineStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteMemberHdrEngineStateTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteMemberHdrEngineStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberHdrEngineStateUpdateCallbackId {
        TicketremoteMemberHdrEngineStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteMemberHdrEngineStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_member_hdr_engine_state`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteMemberHdrEngineStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_member_hdr_engine_state().id().find(...)`.
pub struct TicketremoteMemberHdrEngineStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteMemberHdrEngineState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteMemberHdrEngineStateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_member_hdr_engine_state`.
    pub fn id(&self) -> TicketremoteMemberHdrEngineStateIdUnique<'ctx> {
        TicketremoteMemberHdrEngineStateIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteMemberHdrEngineStateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteMemberHdrEngineState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TicketremoteMemberHdrEngineState>(
        "ticketremote_member_hdr_engine_state",
    );
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteMemberHdrEngineState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteMemberHdrEngineState>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteMemberHdrEngineState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_member_hdr_engine_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteMemberHdrEngineState`.
    fn ticketremote_member_hdr_engine_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteMemberHdrEngineState>;
}

impl ticketremote_member_hdr_engine_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_member_hdr_engine_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteMemberHdrEngineState> {
        __sdk::__query_builder::Table::new("ticketremote_member_hdr_engine_state")
    }
}
