// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteUpdateViviReauthAttemptArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub request_id: String,
    pub credential_revision: String,
    pub status: String,
    pub phase: String,
    pub reason: String,
    pub proof_source: String,
    pub stream_epoch: String,
    pub frame_sequence: String,
    pub now_arg: String,
}

impl From<TicketremoteUpdateViviReauthAttemptArgs> for super::Reducer {
    fn from(args: TicketremoteUpdateViviReauthAttemptArgs) -> Self {
        Self::TicketremoteUpdateViviReauthAttempt {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            request_id: args.request_id,
            credential_revision: args.credential_revision,
            status: args.status,
            phase: args.phase,
            reason: args.reason,
            proof_source: args.proof_source,
            stream_epoch: args.stream_epoch,
            frame_sequence: args.frame_sequence,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteUpdateViviReauthAttemptArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_update_vivi_reauth_attempt`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_update_vivi_reauth_attempt {
    /// Request that the remote module invoke the reducer `ticketremote_update_vivi_reauth_attempt` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_update_vivi_reauth_attempt:ticketremote_update_vivi_reauth_attempt_then`] to run a callback after the reducer completes.
    fn ticketremote_update_vivi_reauth_attempt(
        &self,
        ticket_id: String,
        backend_id: String,
        request_id: String,
        credential_revision: String,
        status: String,
        phase: String,
        reason: String,
        proof_source: String,
        stream_epoch: String,
        frame_sequence: String,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_update_vivi_reauth_attempt_then(
            ticket_id,
            backend_id,
            request_id,
            credential_revision,
            status,
            phase,
            reason,
            proof_source,
            stream_epoch,
            frame_sequence,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_update_vivi_reauth_attempt` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_update_vivi_reauth_attempt_then(
        &self,
        ticket_id: String,
        backend_id: String,
        request_id: String,
        credential_revision: String,
        status: String,
        phase: String,
        reason: String,
        proof_source: String,
        stream_epoch: String,
        frame_sequence: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_update_vivi_reauth_attempt for super::RemoteReducers {
    fn ticketremote_update_vivi_reauth_attempt_then(
        &self,
        ticket_id: String,
        backend_id: String,
        request_id: String,
        credential_revision: String,
        status: String,
        phase: String,
        reason: String,
        proof_source: String,
        stream_epoch: String,
        frame_sequence: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteUpdateViviReauthAttemptArgs {
                ticket_id,
                backend_id,
                request_id,
                credential_revision,
                status,
                phase,
                reason,
                proof_source,
                stream_epoch,
                frame_sequence,
                now_arg,
            },
            callback,
        )
    }
}
