// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteViviCredentialState {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub configured: bool,
    pub revision: String,
    pub updated_at: String,
}

impl __sdk::InModule for TicketremoteViviCredentialState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteViviCredentialState`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteViviCredentialStateCols {
    pub id: __sdk::__query_builder::Col<TicketremoteViviCredentialState, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteViviCredentialState, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteViviCredentialState, String>,
    pub configured: __sdk::__query_builder::Col<TicketremoteViviCredentialState, bool>,
    pub revision: __sdk::__query_builder::Col<TicketremoteViviCredentialState, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteViviCredentialState, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteViviCredentialState {
    type Cols = TicketremoteViviCredentialStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteViviCredentialStateCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            configured: __sdk::__query_builder::Col::new(table_name, "configured"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteViviCredentialState`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteViviCredentialStateIxCols {
    pub id: __sdk::__query_builder::IxCol<TicketremoteViviCredentialState, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteViviCredentialState {
    type IxCols = TicketremoteViviCredentialStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteViviCredentialStateIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteViviCredentialState {}
