// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteRevokeControlArgs {
    pub ticket_id: String,
    pub actor_email: String,
    pub reason: String,
    pub now_arg: String,
}

impl From<TicketremoteRevokeControlArgs> for super::Reducer {
    fn from(args: TicketremoteRevokeControlArgs) -> Self {
        Self::TicketremoteRevokeControl {
            ticket_id: args.ticket_id,
            actor_email: args.actor_email,
            reason: args.reason,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteRevokeControlArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_revoke_control`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_revoke_control {
    /// Request that the remote module invoke the reducer `ticketremote_revoke_control` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_revoke_control:ticketremote_revoke_control_then`] to run a callback after the reducer completes.
    fn ticketremote_revoke_control(
        &self,
        ticket_id: String,
        actor_email: String,
        reason: String,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_revoke_control_then(ticket_id, actor_email, reason, now_arg, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ticketremote_revoke_control` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_revoke_control_then(
        &self,
        ticket_id: String,
        actor_email: String,
        reason: String,
        now_arg: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_revoke_control for super::RemoteReducers {
    fn ticketremote_revoke_control_then(
        &self,
        ticket_id: String,
        actor_email: String,
        reason: String,
        now_arg: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteRevokeControlArgs {
                ticket_id,
                actor_email,
                reason,
                now_arg,
            },
            callback,
        )
    }
}
