// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteFinishPushDeliveryArgs {
    pub ticket_id: String,
    pub delivery_id: String,
    pub claim_id: String,
    pub outcome: String,
}

impl From<TicketremoteFinishPushDeliveryArgs> for super::Reducer {
    fn from(args: TicketremoteFinishPushDeliveryArgs) -> Self {
        Self::TicketremoteFinishPushDelivery {
            ticket_id: args.ticket_id,
            delivery_id: args.delivery_id,
            claim_id: args.claim_id,
            outcome: args.outcome,
        }
    }
}

impl __sdk::InModule for TicketremoteFinishPushDeliveryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_finish_push_delivery`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_finish_push_delivery {
    /// Request that the remote module invoke the reducer `ticketremote_finish_push_delivery` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_finish_push_delivery:ticketremote_finish_push_delivery_then`] to run a callback after the reducer completes.
    fn ticketremote_finish_push_delivery(
        &self,
        ticket_id: String,
        delivery_id: String,
        claim_id: String,
        outcome: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_finish_push_delivery_then(
            ticket_id,
            delivery_id,
            claim_id,
            outcome,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_finish_push_delivery` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_finish_push_delivery_then(
        &self,
        ticket_id: String,
        delivery_id: String,
        claim_id: String,
        outcome: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_finish_push_delivery for super::RemoteReducers {
    fn ticketremote_finish_push_delivery_then(
        &self,
        ticket_id: String,
        delivery_id: String,
        claim_id: String,
        outcome: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteFinishPushDeliveryArgs {
                ticket_id,
                delivery_id,
                claim_id,
                outcome,
            },
            callback,
        )
    }
}
