// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberAppendDevPerfMetricArgs {
    pub ticket_id: String,
    pub metric_name: String,
    pub phase: String,
    pub flow_id: String,
    pub value_millis: u32,
    pub ok: bool,
    pub detail_json: String,
}

impl From<TicketremoteMemberAppendDevPerfMetricArgs> for super::Reducer {
    fn from(args: TicketremoteMemberAppendDevPerfMetricArgs) -> Self {
        Self::TicketremoteMemberAppendDevPerfMetric {
            ticket_id: args.ticket_id,
            metric_name: args.metric_name,
            phase: args.phase,
            flow_id: args.flow_id,
            value_millis: args.value_millis,
            ok: args.ok,
            detail_json: args.detail_json,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberAppendDevPerfMetricArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_append_dev_perf_metric`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_append_dev_perf_metric {
    /// Request that the remote module invoke the reducer `ticketremote_member_append_dev_perf_metric` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_append_dev_perf_metric:ticketremote_member_append_dev_perf_metric_then`] to run a callback after the reducer completes.
    fn ticketremote_member_append_dev_perf_metric(
        &self,
        ticket_id: String,
        metric_name: String,
        phase: String,
        flow_id: String,
        value_millis: u32,
        ok: bool,
        detail_json: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_append_dev_perf_metric_then(
            ticket_id,
            metric_name,
            phase,
            flow_id,
            value_millis,
            ok,
            detail_json,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_append_dev_perf_metric` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_append_dev_perf_metric_then(
        &self,
        ticket_id: String,
        metric_name: String,
        phase: String,
        flow_id: String,
        value_millis: u32,
        ok: bool,
        detail_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_append_dev_perf_metric for super::RemoteReducers {
    fn ticketremote_member_append_dev_perf_metric_then(
        &self,
        ticket_id: String,
        metric_name: String,
        phase: String,
        flow_id: String,
        value_millis: u32,
        ok: bool,
        detail_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberAppendDevPerfMetricArgs {
                ticket_id,
                metric_name,
                phase,
                flow_id,
                value_millis,
                ok,
                detail_json,
            },
            callback,
        )
    }
}
