// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_service_viewer_type::TicketremoteServiceViewer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_service_viewer_presence`.
///
/// Obtain a handle from the [`TicketremoteServiceViewerPresenceTableAccess::ticketremote_service_viewer_presence`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_service_viewer_presence()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_viewer_presence().on_insert(...)`.
pub struct TicketremoteServiceViewerPresenceTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteServiceViewer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_service_viewer_presence`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteServiceViewerPresenceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteServiceViewerPresenceTableHandle`], which mediates access to the table `ticketremote_service_viewer_presence`.
    fn ticketremote_service_viewer_presence(
        &self,
    ) -> TicketremoteServiceViewerPresenceTableHandle<'_>;
}

impl TicketremoteServiceViewerPresenceTableAccess for super::RemoteTables {
    fn ticketremote_service_viewer_presence(
        &self,
    ) -> TicketremoteServiceViewerPresenceTableHandle<'_> {
        TicketremoteServiceViewerPresenceTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteServiceViewer>("ticketremote_service_viewer_presence"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteServiceViewerPresenceInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteServiceViewerPresenceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteServiceViewerPresenceTableHandle<'ctx> {
    type Row = TicketremoteServiceViewer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteServiceViewer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteServiceViewerPresenceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceViewerPresenceInsertCallbackId {
        TicketremoteServiceViewerPresenceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteServiceViewerPresenceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteServiceViewerPresenceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceViewerPresenceDeleteCallbackId {
        TicketremoteServiceViewerPresenceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteServiceViewerPresenceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteServiceViewerPresenceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteServiceViewerPresenceTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteServiceViewerPresenceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceViewerPresenceUpdateCallbackId {
        TicketremoteServiceViewerPresenceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteServiceViewerPresenceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `session_id` unique index on the table `ticketremote_service_viewer_presence`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteServiceViewerPresenceSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_viewer_presence().session_id().find(...)`.
pub struct TicketremoteServiceViewerPresenceSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteServiceViewer, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteServiceViewerPresenceTableHandle<'ctx> {
    /// Get a handle on the `session_id` unique index on the table `ticketremote_service_viewer_presence`.
    pub fn session_id(&self) -> TicketremoteServiceViewerPresenceSessionIdUnique<'ctx> {
        TicketremoteServiceViewerPresenceSessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteServiceViewerPresenceSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `session_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteServiceViewer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremoteServiceViewer>("ticketremote_service_viewer_presence");
    _table.add_unique_constraint::<String>("session_id", |row| &row.session_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteServiceViewer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TicketremoteServiceViewer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteServiceViewer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_service_viewer_presenceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteServiceViewer`.
    fn ticketremote_service_viewer_presence(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceViewer>;
}

impl ticketremote_service_viewer_presenceQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_service_viewer_presence(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceViewer> {
        __sdk::__query_builder::Table::new("ticketremote_service_viewer_presence")
    }
}
