// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteScheduleLatestTicketReselectV3Args {
    pub ticket_id: String,
    pub backend_id: String,
    pub schedule_id: String,
    pub scheduled_at_micros: i64,
    pub phone_local_time: String,
    pub phone_time_zone: String,
    pub requested_by: String,
    pub target: String,
    pub now_arg: String,
}

impl From<TicketremoteScheduleLatestTicketReselectV3Args> for super::Reducer {
    fn from(args: TicketremoteScheduleLatestTicketReselectV3Args) -> Self {
        Self::TicketremoteScheduleLatestTicketReselectV3 {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            schedule_id: args.schedule_id,
            scheduled_at_micros: args.scheduled_at_micros,
            phone_local_time: args.phone_local_time,
            phone_time_zone: args.phone_time_zone,
            requested_by: args.requested_by,
            target: args.target,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteScheduleLatestTicketReselectV3Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_schedule_latest_ticket_reselect_v3`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_schedule_latest_ticket_reselect_v_3 {
    /// Request that the remote module invoke the reducer `ticketremote_schedule_latest_ticket_reselect_v3` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_schedule_latest_ticket_reselect_v_3:ticketremote_schedule_latest_ticket_reselect_v_3_then`] to run a callback after the reducer completes.
    fn ticketremote_schedule_latest_ticket_reselect_v_3(
        &self,
        ticket_id: String,
        backend_id: String,
        schedule_id: String,
        scheduled_at_micros: i64,
        phone_local_time: String,
        phone_time_zone: String,
        requested_by: String,
        target: String,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_schedule_latest_ticket_reselect_v_3_then(
            ticket_id,
            backend_id,
            schedule_id,
            scheduled_at_micros,
            phone_local_time,
            phone_time_zone,
            requested_by,
            target,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_schedule_latest_ticket_reselect_v3` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_schedule_latest_ticket_reselect_v_3_then(
        &self,
        ticket_id: String,
        backend_id: String,
        schedule_id: String,
        scheduled_at_micros: i64,
        phone_local_time: String,
        phone_time_zone: String,
        requested_by: String,
        target: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_schedule_latest_ticket_reselect_v_3 for super::RemoteReducers {
    fn ticketremote_schedule_latest_ticket_reselect_v_3_then(
        &self,
        ticket_id: String,
        backend_id: String,
        schedule_id: String,
        scheduled_at_micros: i64,
        phone_local_time: String,
        phone_time_zone: String,
        requested_by: String,
        target: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteScheduleLatestTicketReselectV3Args {
                ticket_id,
                backend_id,
                schedule_id,
                scheduled_at_micros,
                phone_local_time,
                phone_time_zone,
                requested_by,
                target,
                now_arg,
            },
            callback,
        )
    }
}
