// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_service_member_account_type::TicketremoteServiceMemberAccount;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_service_member_account`.
///
/// Obtain a handle from the [`TicketremoteServiceMemberAccountTableAccess::ticketremote_service_member_account`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_service_member_account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_member_account().on_insert(...)`.
pub struct TicketremoteServiceMemberAccountTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteServiceMemberAccount>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_service_member_account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteServiceMemberAccountTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteServiceMemberAccountTableHandle`], which mediates access to the table `ticketremote_service_member_account`.
    fn ticketremote_service_member_account(
        &self,
    ) -> TicketremoteServiceMemberAccountTableHandle<'_>;
}

impl TicketremoteServiceMemberAccountTableAccess for super::RemoteTables {
    fn ticketremote_service_member_account(
        &self,
    ) -> TicketremoteServiceMemberAccountTableHandle<'_> {
        TicketremoteServiceMemberAccountTableHandle {
            imp: self.imp.get_table::<TicketremoteServiceMemberAccount>(
                "ticketremote_service_member_account",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteServiceMemberAccountInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteServiceMemberAccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteServiceMemberAccountTableHandle<'ctx> {
    type Row = TicketremoteServiceMemberAccount;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteServiceMemberAccount> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteServiceMemberAccountInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceMemberAccountInsertCallbackId {
        TicketremoteServiceMemberAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteServiceMemberAccountInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteServiceMemberAccountDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceMemberAccountDeleteCallbackId {
        TicketremoteServiceMemberAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteServiceMemberAccountDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteServiceMemberAccountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteServiceMemberAccountTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteServiceMemberAccountUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceMemberAccountUpdateCallbackId {
        TicketremoteServiceMemberAccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteServiceMemberAccountUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_service_member_account`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteServiceMemberAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_member_account().id().find(...)`.
pub struct TicketremoteServiceMemberAccountIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteServiceMemberAccount, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteServiceMemberAccountTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_service_member_account`.
    pub fn id(&self) -> TicketremoteServiceMemberAccountIdUnique<'ctx> {
        TicketremoteServiceMemberAccountIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteServiceMemberAccountIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteServiceMemberAccount> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TicketremoteServiceMemberAccount>(
        "ticketremote_service_member_account",
    );
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteServiceMemberAccount>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteServiceMemberAccount>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteServiceMemberAccount`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_service_member_accountQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteServiceMemberAccount`.
    fn ticketremote_service_member_account(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceMemberAccount>;
}

impl ticketremote_service_member_accountQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_service_member_account(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceMemberAccount> {
        __sdk::__query_builder::Table::new("ticketremote_service_member_account")
    }
}
