// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteTicketInteraction {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub status: String,
    pub interaction_revision: String,
    pub activation_revision: String,
    pub activation_at: String,
    pub scheduled_reset_at: String,
    pub reset_request_id: String,
    pub stream_epoch: String,
    pub frame_sequence: String,
    pub phone_display_width: u32,
    pub phone_display_height: u32,
    pub slider_left: u32,
    pub slider_top: u32,
    pub slider_right: u32,
    pub slider_bottom: u32,
    pub owner_public_id: String,
    pub control_id: String,
    pub lease_phase: String,
    pub lease_expires_at: String,
    pub latest_input_sequence: String,
    pub latest_input_phase: String,
    pub latest_progress: u32,
    pub last_applied_sequence: String,
    pub last_applied_progress: u32,
    pub reason: String,
    pub created_at: String,
    pub updated_at: String,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteTicketInteraction {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteTicketInteraction`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteTicketInteractionCols {
    pub id: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub status: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub interaction_revision: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub activation_revision: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub activation_at: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub scheduled_reset_at: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub reset_request_id: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub stream_epoch: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub frame_sequence: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub phone_display_width: __sdk::__query_builder::Col<TicketremoteTicketInteraction, u32>,
    pub phone_display_height: __sdk::__query_builder::Col<TicketremoteTicketInteraction, u32>,
    pub slider_left: __sdk::__query_builder::Col<TicketremoteTicketInteraction, u32>,
    pub slider_top: __sdk::__query_builder::Col<TicketremoteTicketInteraction, u32>,
    pub slider_right: __sdk::__query_builder::Col<TicketremoteTicketInteraction, u32>,
    pub slider_bottom: __sdk::__query_builder::Col<TicketremoteTicketInteraction, u32>,
    pub owner_public_id: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub control_id: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub lease_phase: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub lease_expires_at: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub latest_input_sequence: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub latest_input_phase: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub latest_progress: __sdk::__query_builder::Col<TicketremoteTicketInteraction, u32>,
    pub last_applied_sequence: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub last_applied_progress: __sdk::__query_builder::Col<TicketremoteTicketInteraction, u32>,
    pub reason: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub created_at: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteTicketInteraction, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteTicketInteraction {
    type Cols = TicketremoteTicketInteractionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteTicketInteractionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            interaction_revision: __sdk::__query_builder::Col::new(
                table_name,
                "interaction_revision",
            ),
            activation_revision: __sdk::__query_builder::Col::new(
                table_name,
                "activation_revision",
            ),
            activation_at: __sdk::__query_builder::Col::new(table_name, "activation_at"),
            scheduled_reset_at: __sdk::__query_builder::Col::new(table_name, "scheduled_reset_at"),
            reset_request_id: __sdk::__query_builder::Col::new(table_name, "reset_request_id"),
            stream_epoch: __sdk::__query_builder::Col::new(table_name, "stream_epoch"),
            frame_sequence: __sdk::__query_builder::Col::new(table_name, "frame_sequence"),
            phone_display_width: __sdk::__query_builder::Col::new(
                table_name,
                "phone_display_width",
            ),
            phone_display_height: __sdk::__query_builder::Col::new(
                table_name,
                "phone_display_height",
            ),
            slider_left: __sdk::__query_builder::Col::new(table_name, "slider_left"),
            slider_top: __sdk::__query_builder::Col::new(table_name, "slider_top"),
            slider_right: __sdk::__query_builder::Col::new(table_name, "slider_right"),
            slider_bottom: __sdk::__query_builder::Col::new(table_name, "slider_bottom"),
            owner_public_id: __sdk::__query_builder::Col::new(table_name, "owner_public_id"),
            control_id: __sdk::__query_builder::Col::new(table_name, "control_id"),
            lease_phase: __sdk::__query_builder::Col::new(table_name, "lease_phase"),
            lease_expires_at: __sdk::__query_builder::Col::new(table_name, "lease_expires_at"),
            latest_input_sequence: __sdk::__query_builder::Col::new(
                table_name,
                "latest_input_sequence",
            ),
            latest_input_phase: __sdk::__query_builder::Col::new(table_name, "latest_input_phase"),
            latest_progress: __sdk::__query_builder::Col::new(table_name, "latest_progress"),
            last_applied_sequence: __sdk::__query_builder::Col::new(
                table_name,
                "last_applied_sequence",
            ),
            last_applied_progress: __sdk::__query_builder::Col::new(
                table_name,
                "last_applied_progress",
            ),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteTicketInteraction`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteTicketInteractionIxCols {
    pub backend_id: __sdk::__query_builder::IxCol<TicketremoteTicketInteraction, String>,
    pub expires_at: __sdk::__query_builder::IxCol<TicketremoteTicketInteraction, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteTicketInteraction, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteTicketInteraction, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteTicketInteraction {
    type IxCols = TicketremoteTicketInteractionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteTicketInteractionIxCols {
            backend_id: __sdk::__query_builder::IxCol::new(table_name, "backend_id"),
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteTicketInteraction {}
