// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteRetryTicketActionV3AfterNoTransitionArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub parent_action_id: String,
    pub interaction_revision: String,
    pub stream_epoch: String,
    pub frame_sequence: String,
    pub now_arg: String,
}

impl From<TicketremoteRetryTicketActionV3AfterNoTransitionArgs> for super::Reducer {
    fn from(args: TicketremoteRetryTicketActionV3AfterNoTransitionArgs) -> Self {
        Self::TicketremoteRetryTicketActionV3AfterNoTransition {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            parent_action_id: args.parent_action_id,
            interaction_revision: args.interaction_revision,
            stream_epoch: args.stream_epoch,
            frame_sequence: args.frame_sequence,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteRetryTicketActionV3AfterNoTransitionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_retry_ticket_action_v3_after_no_transition`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_retry_ticket_action_v_3_after_no_transition {
    /// Request that the remote module invoke the reducer `ticketremote_retry_ticket_action_v3_after_no_transition` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_retry_ticket_action_v_3_after_no_transition:ticketremote_retry_ticket_action_v_3_after_no_transition_then`] to run a callback after the reducer completes.
    fn ticketremote_retry_ticket_action_v_3_after_no_transition(
        &self,
        ticket_id: String,
        backend_id: String,
        parent_action_id: String,
        interaction_revision: String,
        stream_epoch: String,
        frame_sequence: String,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_retry_ticket_action_v_3_after_no_transition_then(
            ticket_id,
            backend_id,
            parent_action_id,
            interaction_revision,
            stream_epoch,
            frame_sequence,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_retry_ticket_action_v3_after_no_transition` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_retry_ticket_action_v_3_after_no_transition_then(
        &self,
        ticket_id: String,
        backend_id: String,
        parent_action_id: String,
        interaction_revision: String,
        stream_epoch: String,
        frame_sequence: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_retry_ticket_action_v_3_after_no_transition for super::RemoteReducers {
    fn ticketremote_retry_ticket_action_v_3_after_no_transition_then(
        &self,
        ticket_id: String,
        backend_id: String,
        parent_action_id: String,
        interaction_revision: String,
        stream_epoch: String,
        frame_sequence: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteRetryTicketActionV3AfterNoTransitionArgs {
                ticket_id,
                backend_id,
                parent_action_id,
                interaction_revision,
                stream_epoch,
                frame_sequence,
                now_arg,
            },
            callback,
        )
    }
}
