// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberCheckInArgs {
    pub ticket_id: String,
    pub request_id: String,
    pub expected_revision: String,
    pub direction: String,
    pub carriage: u8,
}

impl From<TicketremoteMemberCheckInArgs> for super::Reducer {
    fn from(args: TicketremoteMemberCheckInArgs) -> Self {
        Self::TicketremoteMemberCheckIn {
            ticket_id: args.ticket_id,
            request_id: args.request_id,
            expected_revision: args.expected_revision,
            direction: args.direction,
            carriage: args.carriage,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberCheckInArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_check_in`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_check_in {
    /// Request that the remote module invoke the reducer `ticketremote_member_check_in` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_check_in:ticketremote_member_check_in_then`] to run a callback after the reducer completes.
    fn ticketremote_member_check_in(
        &self,
        ticket_id: String,
        request_id: String,
        expected_revision: String,
        direction: String,
        carriage: u8,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_check_in_then(
            ticket_id,
            request_id,
            expected_revision,
            direction,
            carriage,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_check_in` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_check_in_then(
        &self,
        ticket_id: String,
        request_id: String,
        expected_revision: String,
        direction: String,
        carriage: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_check_in for super::RemoteReducers {
    fn ticketremote_member_check_in_then(
        &self,
        ticket_id: String,
        request_id: String,
        expected_revision: String,
        direction: String,
        carriage: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberCheckInArgs {
                ticket_id,
                request_id,
                expected_revision,
                direction,
                carriage,
            },
            callback,
        )
    }
}
