// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberClaimTicketSliderArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub interaction_revision: String,
    pub control_id: String,
    pub initial_input_sequence: String,
    pub hold_duration_millis: u32,
    pub horizontal_travel_css: u32,
    pub vertical_travel_css: u32,
    pub initial_progress: u32,
}

impl From<TicketremoteMemberClaimTicketSliderArgs> for super::Reducer {
    fn from(args: TicketremoteMemberClaimTicketSliderArgs) -> Self {
        Self::TicketremoteMemberClaimTicketSlider {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            interaction_revision: args.interaction_revision,
            control_id: args.control_id,
            initial_input_sequence: args.initial_input_sequence,
            hold_duration_millis: args.hold_duration_millis,
            horizontal_travel_css: args.horizontal_travel_css,
            vertical_travel_css: args.vertical_travel_css,
            initial_progress: args.initial_progress,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberClaimTicketSliderArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_claim_ticket_slider`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_claim_ticket_slider {
    /// Request that the remote module invoke the reducer `ticketremote_member_claim_ticket_slider` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_claim_ticket_slider:ticketremote_member_claim_ticket_slider_then`] to run a callback after the reducer completes.
    fn ticketremote_member_claim_ticket_slider(
        &self,
        ticket_id: String,
        backend_id: String,
        interaction_revision: String,
        control_id: String,
        initial_input_sequence: String,
        hold_duration_millis: u32,
        horizontal_travel_css: u32,
        vertical_travel_css: u32,
        initial_progress: u32,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_claim_ticket_slider_then(
            ticket_id,
            backend_id,
            interaction_revision,
            control_id,
            initial_input_sequence,
            hold_duration_millis,
            horizontal_travel_css,
            vertical_travel_css,
            initial_progress,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_claim_ticket_slider` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_claim_ticket_slider_then(
        &self,
        ticket_id: String,
        backend_id: String,
        interaction_revision: String,
        control_id: String,
        initial_input_sequence: String,
        hold_duration_millis: u32,
        horizontal_travel_css: u32,
        vertical_travel_css: u32,
        initial_progress: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_claim_ticket_slider for super::RemoteReducers {
    fn ticketremote_member_claim_ticket_slider_then(
        &self,
        ticket_id: String,
        backend_id: String,
        interaction_revision: String,
        control_id: String,
        initial_input_sequence: String,
        hold_duration_millis: u32,
        horizontal_travel_css: u32,
        vertical_travel_css: u32,
        initial_progress: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberClaimTicketSliderArgs {
                ticket_id,
                backend_id,
                interaction_revision,
                control_id,
                initial_input_sequence,
                hold_duration_millis,
                horizontal_travel_css,
                vertical_travel_css,
                initial_progress,
            },
            callback,
        )
    }
}
