// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteScheduleActivationExpiryResetArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub activation_revision: String,
    pub now_arg: String,
}

impl From<TicketremoteScheduleActivationExpiryResetArgs> for super::Reducer {
    fn from(args: TicketremoteScheduleActivationExpiryResetArgs) -> Self {
        Self::TicketremoteScheduleActivationExpiryReset {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            activation_revision: args.activation_revision,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteScheduleActivationExpiryResetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_schedule_activation_expiry_reset`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_schedule_activation_expiry_reset {
    /// Request that the remote module invoke the reducer `ticketremote_schedule_activation_expiry_reset` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_schedule_activation_expiry_reset:ticketremote_schedule_activation_expiry_reset_then`] to run a callback after the reducer completes.
    fn ticketremote_schedule_activation_expiry_reset(
        &self,
        ticket_id: String,
        backend_id: String,
        activation_revision: String,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_schedule_activation_expiry_reset_then(
            ticket_id,
            backend_id,
            activation_revision,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_schedule_activation_expiry_reset` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_schedule_activation_expiry_reset_then(
        &self,
        ticket_id: String,
        backend_id: String,
        activation_revision: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_schedule_activation_expiry_reset for super::RemoteReducers {
    fn ticketremote_schedule_activation_expiry_reset_then(
        &self,
        ticket_id: String,
        backend_id: String,
        activation_revision: String,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteScheduleActivationExpiryResetArgs {
                ticket_id,
                backend_id,
                activation_revision,
                now_arg,
            },
            callback,
        )
    }
}
