// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteUpdatePhoneStatusArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub attach_name: String,
    pub base_url: String,
    pub desired_state: String,
    pub health_json: String,
    pub last_error: String,
    pub now_arg: String,
}

impl From<TicketremoteUpdatePhoneStatusArgs> for super::Reducer {
    fn from(args: TicketremoteUpdatePhoneStatusArgs) -> Self {
        Self::TicketremoteUpdatePhoneStatus {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            attach_name: args.attach_name,
            base_url: args.base_url,
            desired_state: args.desired_state,
            health_json: args.health_json,
            last_error: args.last_error,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteUpdatePhoneStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_update_phone_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_update_phone_status {
    /// Request that the remote module invoke the reducer `ticketremote_update_phone_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_update_phone_status:ticketremote_update_phone_status_then`] to run a callback after the reducer completes.
    fn ticketremote_update_phone_status(
        &self,
        ticket_id: String,
        backend_id: String,
        attach_name: String,
        base_url: String,
        desired_state: String,
        health_json: String,
        last_error: String,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_update_phone_status_then(
            ticket_id,
            backend_id,
            attach_name,
            base_url,
            desired_state,
            health_json,
            last_error,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_update_phone_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_update_phone_status_then(
        &self,
        ticket_id: String,
        backend_id: String,
        attach_name: String,
        base_url: String,
        desired_state: String,
        health_json: String,
        last_error: String,
        now_arg: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_update_phone_status for super::RemoteReducers {
    fn ticketremote_update_phone_status_then(
        &self,
        ticket_id: String,
        backend_id: String,
        attach_name: String,
        base_url: String,
        desired_state: String,
        health_json: String,
        last_error: String,
        now_arg: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteUpdatePhoneStatusArgs {
                ticket_id,
                backend_id,
                attach_name,
                base_url,
                desired_state,
                health_json,
                last_error,
                now_arg,
            },
            callback,
        )
    }
}
