// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_service_member_daily_activity_type::TicketremoteServiceMemberDailyActivity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_service_member_daily_activity`.
///
/// Obtain a handle from the [`TicketremoteServiceMemberDailyActivityTableAccess::ticketremote_service_member_daily_activity`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_service_member_daily_activity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_member_daily_activity().on_insert(...)`.
pub struct TicketremoteServiceMemberDailyActivityTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteServiceMemberDailyActivity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_service_member_daily_activity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteServiceMemberDailyActivityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteServiceMemberDailyActivityTableHandle`], which mediates access to the table `ticketremote_service_member_daily_activity`.
    fn ticketremote_service_member_daily_activity(
        &self,
    ) -> TicketremoteServiceMemberDailyActivityTableHandle<'_>;
}

impl TicketremoteServiceMemberDailyActivityTableAccess for super::RemoteTables {
    fn ticketremote_service_member_daily_activity(
        &self,
    ) -> TicketremoteServiceMemberDailyActivityTableHandle<'_> {
        TicketremoteServiceMemberDailyActivityTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteServiceMemberDailyActivity>(
                    "ticketremote_service_member_daily_activity",
                ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteServiceMemberDailyActivityInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteServiceMemberDailyActivityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteServiceMemberDailyActivityTableHandle<'ctx> {
    type Row = TicketremoteServiceMemberDailyActivity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteServiceMemberDailyActivity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteServiceMemberDailyActivityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceMemberDailyActivityInsertCallbackId {
        TicketremoteServiceMemberDailyActivityInsertCallbackId(
            self.imp.on_insert(Box::new(callback)),
        )
    }

    fn remove_on_insert(&self, callback: TicketremoteServiceMemberDailyActivityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteServiceMemberDailyActivityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceMemberDailyActivityDeleteCallbackId {
        TicketremoteServiceMemberDailyActivityDeleteCallbackId(
            self.imp.on_delete(Box::new(callback)),
        )
    }

    fn remove_on_delete(&self, callback: TicketremoteServiceMemberDailyActivityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteServiceMemberDailyActivityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteServiceMemberDailyActivityTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteServiceMemberDailyActivityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceMemberDailyActivityUpdateCallbackId {
        TicketremoteServiceMemberDailyActivityUpdateCallbackId(
            self.imp.on_update(Box::new(callback)),
        )
    }

    fn remove_on_update(&self, callback: TicketremoteServiceMemberDailyActivityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_service_member_daily_activity`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteServiceMemberDailyActivityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_member_daily_activity().id().find(...)`.
pub struct TicketremoteServiceMemberDailyActivityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteServiceMemberDailyActivity, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteServiceMemberDailyActivityTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_service_member_daily_activity`.
    pub fn id(&self) -> TicketremoteServiceMemberDailyActivityIdUnique<'ctx> {
        TicketremoteServiceMemberDailyActivityIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteServiceMemberDailyActivityIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteServiceMemberDailyActivity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TicketremoteServiceMemberDailyActivity>(
        "ticketremote_service_member_daily_activity",
    );
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteServiceMemberDailyActivity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteServiceMemberDailyActivity>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteServiceMemberDailyActivity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_service_member_daily_activityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteServiceMemberDailyActivity`.
    fn ticketremote_service_member_daily_activity(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceMemberDailyActivity>;
}

impl ticketremote_service_member_daily_activityQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_service_member_daily_activity(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceMemberDailyActivity> {
        __sdk::__query_builder::Table::new("ticketremote_service_member_daily_activity")
    }
}
