// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteMemberDailyActivity {
    pub id: String,
    pub ticket_id: String,
    pub account_scope_id: String,
    pub day: String,
    pub hourly_ticks: Vec<u32>,
    pub last_tick_slot: i64,
    pub first_tick_at: String,
    pub last_tick_at: String,
    pub updated_at: String,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteMemberDailyActivity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteMemberDailyActivity`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteMemberDailyActivityCols {
    pub id: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, String>,
    pub account_scope_id: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, String>,
    pub day: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, String>,
    pub hourly_ticks: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, Vec<u32>>,
    pub last_tick_slot: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, i64>,
    pub first_tick_at: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, String>,
    pub last_tick_at: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteMemberDailyActivity, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteMemberDailyActivity {
    type Cols = TicketremoteMemberDailyActivityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteMemberDailyActivityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            account_scope_id: __sdk::__query_builder::Col::new(table_name, "account_scope_id"),
            day: __sdk::__query_builder::Col::new(table_name, "day"),
            hourly_ticks: __sdk::__query_builder::Col::new(table_name, "hourly_ticks"),
            last_tick_slot: __sdk::__query_builder::Col::new(table_name, "last_tick_slot"),
            first_tick_at: __sdk::__query_builder::Col::new(table_name, "first_tick_at"),
            last_tick_at: __sdk::__query_builder::Col::new(table_name, "last_tick_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteMemberDailyActivity`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteMemberDailyActivityIxCols {
    pub id: __sdk::__query_builder::IxCol<TicketremoteMemberDailyActivity, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteMemberDailyActivity {
    type IxCols = TicketremoteMemberDailyActivityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteMemberDailyActivityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteMemberDailyActivity {}
