// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_activation_decision_type::TicketremoteActivationDecision;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_activation_decision`.
///
/// Obtain a handle from the [`TicketremoteActivationDecisionTableAccess::ticketremote_activation_decision`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_activation_decision()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_activation_decision().on_insert(...)`.
pub struct TicketremoteActivationDecisionTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteActivationDecision>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_activation_decision`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteActivationDecisionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteActivationDecisionTableHandle`], which mediates access to the table `ticketremote_activation_decision`.
    fn ticketremote_activation_decision(&self) -> TicketremoteActivationDecisionTableHandle<'_>;
}

impl TicketremoteActivationDecisionTableAccess for super::RemoteTables {
    fn ticketremote_activation_decision(&self) -> TicketremoteActivationDecisionTableHandle<'_> {
        TicketremoteActivationDecisionTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteActivationDecision>("ticketremote_activation_decision"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteActivationDecisionInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteActivationDecisionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteActivationDecisionTableHandle<'ctx> {
    type Row = TicketremoteActivationDecision;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteActivationDecision> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteActivationDecisionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteActivationDecisionInsertCallbackId {
        TicketremoteActivationDecisionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteActivationDecisionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteActivationDecisionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteActivationDecisionDeleteCallbackId {
        TicketremoteActivationDecisionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteActivationDecisionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteActivationDecisionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteActivationDecisionTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteActivationDecisionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteActivationDecisionUpdateCallbackId {
        TicketremoteActivationDecisionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteActivationDecisionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_activation_decision`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteActivationDecisionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_activation_decision().id().find(...)`.
pub struct TicketremoteActivationDecisionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteActivationDecision, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteActivationDecisionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_activation_decision`.
    pub fn id(&self) -> TicketremoteActivationDecisionIdUnique<'ctx> {
        TicketremoteActivationDecisionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteActivationDecisionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteActivationDecision> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremoteActivationDecision>("ticketremote_activation_decision");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteActivationDecision>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteActivationDecision>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteActivationDecision`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_activation_decisionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteActivationDecision`.
    fn ticketremote_activation_decision(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteActivationDecision>;
}

impl ticketremote_activation_decisionQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_activation_decision(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteActivationDecision> {
        __sdk::__query_builder::Table::new("ticketremote_activation_decision")
    }
}
