// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_stream_desired_state_type::TicketremoteStreamDesiredState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_stream_desired_state`.
///
/// Obtain a handle from the [`TicketremoteStreamDesiredStateTableAccess::ticketremote_stream_desired_state`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_stream_desired_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_stream_desired_state().on_insert(...)`.
pub struct TicketremoteStreamDesiredStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteStreamDesiredState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_stream_desired_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteStreamDesiredStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteStreamDesiredStateTableHandle`], which mediates access to the table `ticketremote_stream_desired_state`.
    fn ticketremote_stream_desired_state(&self) -> TicketremoteStreamDesiredStateTableHandle<'_>;
}

impl TicketremoteStreamDesiredStateTableAccess for super::RemoteTables {
    fn ticketremote_stream_desired_state(&self) -> TicketremoteStreamDesiredStateTableHandle<'_> {
        TicketremoteStreamDesiredStateTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteStreamDesiredState>("ticketremote_stream_desired_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteStreamDesiredStateInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteStreamDesiredStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteStreamDesiredStateTableHandle<'ctx> {
    type Row = TicketremoteStreamDesiredState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteStreamDesiredState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteStreamDesiredStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteStreamDesiredStateInsertCallbackId {
        TicketremoteStreamDesiredStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteStreamDesiredStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteStreamDesiredStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteStreamDesiredStateDeleteCallbackId {
        TicketremoteStreamDesiredStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteStreamDesiredStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteStreamDesiredStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteStreamDesiredStateTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteStreamDesiredStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteStreamDesiredStateUpdateCallbackId {
        TicketremoteStreamDesiredStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteStreamDesiredStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_stream_desired_state`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteStreamDesiredStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_stream_desired_state().id().find(...)`.
pub struct TicketremoteStreamDesiredStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteStreamDesiredState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteStreamDesiredStateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_stream_desired_state`.
    pub fn id(&self) -> TicketremoteStreamDesiredStateIdUnique<'ctx> {
        TicketremoteStreamDesiredStateIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteStreamDesiredStateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteStreamDesiredState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremoteStreamDesiredState>("ticketremote_stream_desired_state");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteStreamDesiredState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteStreamDesiredState>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteStreamDesiredState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_stream_desired_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteStreamDesiredState`.
    fn ticketremote_stream_desired_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteStreamDesiredState>;
}

impl ticketremote_stream_desired_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_stream_desired_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteStreamDesiredState> {
        __sdk::__query_builder::Table::new("ticketremote_stream_desired_state")
    }
}
