// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteUpdateTicketActionV3WithSliderRegionArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub action_id: String,
    pub target: String,
    pub status: String,
    pub phase: String,
    pub current_view: String,
    pub stream_epoch: String,
    pub frame_sequence: String,
    pub reason: String,
    pub completed_at: String,
    pub has_slider_region: bool,
    pub left_basis_points: u32,
    pub top_basis_points: u32,
    pub right_basis_points: u32,
    pub bottom_basis_points: u32,
    pub now_arg: String,
}

impl From<TicketremoteUpdateTicketActionV3WithSliderRegionArgs> for super::Reducer {
    fn from(args: TicketremoteUpdateTicketActionV3WithSliderRegionArgs) -> Self {
        Self::TicketremoteUpdateTicketActionV3WithSliderRegion {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            action_id: args.action_id,
            target: args.target,
            status: args.status,
            phase: args.phase,
            current_view: args.current_view,
            stream_epoch: args.stream_epoch,
            frame_sequence: args.frame_sequence,
            reason: args.reason,
            completed_at: args.completed_at,
            has_slider_region: args.has_slider_region,
            left_basis_points: args.left_basis_points,
            top_basis_points: args.top_basis_points,
            right_basis_points: args.right_basis_points,
            bottom_basis_points: args.bottom_basis_points,
            now_arg: args.now_arg,
        }
    }
}

impl __sdk::InModule for TicketremoteUpdateTicketActionV3WithSliderRegionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_update_ticket_action_v3_with_slider_region`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_update_ticket_action_v_3_with_slider_region {
    /// Request that the remote module invoke the reducer `ticketremote_update_ticket_action_v3_with_slider_region` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_update_ticket_action_v_3_with_slider_region:ticketremote_update_ticket_action_v_3_with_slider_region_then`] to run a callback after the reducer completes.
    fn ticketremote_update_ticket_action_v_3_with_slider_region(
        &self,
        ticket_id: String,
        backend_id: String,
        action_id: String,
        target: String,
        status: String,
        phase: String,
        current_view: String,
        stream_epoch: String,
        frame_sequence: String,
        reason: String,
        completed_at: String,
        has_slider_region: bool,
        left_basis_points: u32,
        top_basis_points: u32,
        right_basis_points: u32,
        bottom_basis_points: u32,
        now_arg: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_update_ticket_action_v_3_with_slider_region_then(
            ticket_id,
            backend_id,
            action_id,
            target,
            status,
            phase,
            current_view,
            stream_epoch,
            frame_sequence,
            reason,
            completed_at,
            has_slider_region,
            left_basis_points,
            top_basis_points,
            right_basis_points,
            bottom_basis_points,
            now_arg,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_update_ticket_action_v3_with_slider_region` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_update_ticket_action_v_3_with_slider_region_then(
        &self,
        ticket_id: String,
        backend_id: String,
        action_id: String,
        target: String,
        status: String,
        phase: String,
        current_view: String,
        stream_epoch: String,
        frame_sequence: String,
        reason: String,
        completed_at: String,
        has_slider_region: bool,
        left_basis_points: u32,
        top_basis_points: u32,
        right_basis_points: u32,
        bottom_basis_points: u32,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_update_ticket_action_v_3_with_slider_region for super::RemoteReducers {
    fn ticketremote_update_ticket_action_v_3_with_slider_region_then(
        &self,
        ticket_id: String,
        backend_id: String,
        action_id: String,
        target: String,
        status: String,
        phase: String,
        current_view: String,
        stream_epoch: String,
        frame_sequence: String,
        reason: String,
        completed_at: String,
        has_slider_region: bool,
        left_basis_points: u32,
        top_basis_points: u32,
        right_basis_points: u32,
        bottom_basis_points: u32,
        now_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteUpdateTicketActionV3WithSliderRegionArgs {
                ticket_id,
                backend_id,
                action_id,
                target,
                status,
                phase,
                current_view,
                stream_epoch,
                frame_sequence,
                reason,
                completed_at,
                has_slider_region,
                left_basis_points,
                top_basis_points,
                right_basis_points,
                bottom_basis_points,
                now_arg,
            },
            callback,
        )
    }
}
