// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteServiceTicket {
    pub id: String,
    pub display_name: String,
    pub updated_at: String,
}

impl __sdk::InModule for TicketremoteServiceTicket {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteServiceTicket`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteServiceTicketCols {
    pub id: __sdk::__query_builder::Col<TicketremoteServiceTicket, String>,
    pub display_name: __sdk::__query_builder::Col<TicketremoteServiceTicket, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteServiceTicket, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteServiceTicket {
    type Cols = TicketremoteServiceTicketCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteServiceTicketCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}
