// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteBeginPhoneControlSessionArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub session_id: String,
    pub expected_previous_session_id: String,
}

impl From<TicketremoteBeginPhoneControlSessionArgs> for super::Reducer {
    fn from(args: TicketremoteBeginPhoneControlSessionArgs) -> Self {
        Self::TicketremoteBeginPhoneControlSession {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            session_id: args.session_id,
            expected_previous_session_id: args.expected_previous_session_id,
        }
    }
}

impl __sdk::InModule for TicketremoteBeginPhoneControlSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_begin_phone_control_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_begin_phone_control_session {
    /// Request that the remote module invoke the reducer `ticketremote_begin_phone_control_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_begin_phone_control_session:ticketremote_begin_phone_control_session_then`] to run a callback after the reducer completes.
    fn ticketremote_begin_phone_control_session(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        expected_previous_session_id: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_begin_phone_control_session_then(
            ticket_id,
            backend_id,
            session_id,
            expected_previous_session_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_begin_phone_control_session` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_begin_phone_control_session_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        expected_previous_session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_begin_phone_control_session for super::RemoteReducers {
    fn ticketremote_begin_phone_control_session_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        expected_previous_session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteBeginPhoneControlSessionArgs {
                ticket_id,
                backend_id,
                session_id,
                expected_previous_session_id,
            },
            callback,
        )
    }
}
