// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_service_safe_operational_log_type::TicketremoteServiceSafeOperationalLog;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_service_safe_operational_log`.
///
/// Obtain a handle from the [`TicketremoteServiceSafeOperationalLogTableAccess::ticketremote_service_safe_operational_log`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_service_safe_operational_log()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_safe_operational_log().on_insert(...)`.
pub struct TicketremoteServiceSafeOperationalLogTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteServiceSafeOperationalLog>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_service_safe_operational_log`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteServiceSafeOperationalLogTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteServiceSafeOperationalLogTableHandle`], which mediates access to the table `ticketremote_service_safe_operational_log`.
    fn ticketremote_service_safe_operational_log(
        &self,
    ) -> TicketremoteServiceSafeOperationalLogTableHandle<'_>;
}

impl TicketremoteServiceSafeOperationalLogTableAccess for super::RemoteTables {
    fn ticketremote_service_safe_operational_log(
        &self,
    ) -> TicketremoteServiceSafeOperationalLogTableHandle<'_> {
        TicketremoteServiceSafeOperationalLogTableHandle {
            imp: self.imp.get_table::<TicketremoteServiceSafeOperationalLog>(
                "ticketremote_service_safe_operational_log",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteServiceSafeOperationalLogInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteServiceSafeOperationalLogDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteServiceSafeOperationalLogTableHandle<'ctx> {
    type Row = TicketremoteServiceSafeOperationalLog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteServiceSafeOperationalLog> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteServiceSafeOperationalLogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceSafeOperationalLogInsertCallbackId {
        TicketremoteServiceSafeOperationalLogInsertCallbackId(
            self.imp.on_insert(Box::new(callback)),
        )
    }

    fn remove_on_insert(&self, callback: TicketremoteServiceSafeOperationalLogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteServiceSafeOperationalLogDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceSafeOperationalLogDeleteCallbackId {
        TicketremoteServiceSafeOperationalLogDeleteCallbackId(
            self.imp.on_delete(Box::new(callback)),
        )
    }

    fn remove_on_delete(&self, callback: TicketremoteServiceSafeOperationalLogDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteServiceSafeOperationalLogUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteServiceSafeOperationalLogTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteServiceSafeOperationalLogUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteServiceSafeOperationalLogUpdateCallbackId {
        TicketremoteServiceSafeOperationalLogUpdateCallbackId(
            self.imp.on_update(Box::new(callback)),
        )
    }

    fn remove_on_update(&self, callback: TicketremoteServiceSafeOperationalLogUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_service_safe_operational_log`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteServiceSafeOperationalLogIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_service_safe_operational_log().id().find(...)`.
pub struct TicketremoteServiceSafeOperationalLogIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteServiceSafeOperationalLog, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteServiceSafeOperationalLogTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_service_safe_operational_log`.
    pub fn id(&self) -> TicketremoteServiceSafeOperationalLogIdUnique<'ctx> {
        TicketremoteServiceSafeOperationalLogIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteServiceSafeOperationalLogIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteServiceSafeOperationalLog> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TicketremoteServiceSafeOperationalLog>(
        "ticketremote_service_safe_operational_log",
    );
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteServiceSafeOperationalLog>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteServiceSafeOperationalLog>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteServiceSafeOperationalLog`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_service_safe_operational_logQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteServiceSafeOperationalLog`.
    fn ticketremote_service_safe_operational_log(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceSafeOperationalLog>;
}

impl ticketremote_service_safe_operational_logQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_service_safe_operational_log(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteServiceSafeOperationalLog> {
        __sdk::__query_builder::Table::new("ticketremote_service_safe_operational_log")
    }
}
