// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteViviReauthOwner {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub request_id: String,
    pub owner_email: String,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteViviReauthOwner {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteViviReauthOwner`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteViviReauthOwnerCols {
    pub id: __sdk::__query_builder::Col<TicketremoteViviReauthOwner, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteViviReauthOwner, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteViviReauthOwner, String>,
    pub request_id: __sdk::__query_builder::Col<TicketremoteViviReauthOwner, String>,
    pub owner_email: __sdk::__query_builder::Col<TicketremoteViviReauthOwner, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteViviReauthOwner, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteViviReauthOwner {
    type Cols = TicketremoteViviReauthOwnerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteViviReauthOwnerCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            owner_email: __sdk::__query_builder::Col::new(table_name, "owner_email"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteViviReauthOwner`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteViviReauthOwnerIxCols {
    pub expires_at: __sdk::__query_builder::IxCol<TicketremoteViviReauthOwner, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteViviReauthOwner, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteViviReauthOwner, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteViviReauthOwner {
    type IxCols = TicketremoteViviReauthOwnerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteViviReauthOwnerIxCols {
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteViviReauthOwner {}
