// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteViviCredentialView {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub email: String,
    pub password: String,
    pub revision: String,
    pub updated_at: String,
}

impl __sdk::InModule for TicketremoteViviCredentialView {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteViviCredentialView`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteViviCredentialViewCols {
    pub id: __sdk::__query_builder::Col<TicketremoteViviCredentialView, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteViviCredentialView, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteViviCredentialView, String>,
    pub email: __sdk::__query_builder::Col<TicketremoteViviCredentialView, String>,
    pub password: __sdk::__query_builder::Col<TicketremoteViviCredentialView, String>,
    pub revision: __sdk::__query_builder::Col<TicketremoteViviCredentialView, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteViviCredentialView, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteViviCredentialView {
    type Cols = TicketremoteViviCredentialViewCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteViviCredentialViewCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            password: __sdk::__query_builder::Col::new(table_name, "password"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}
