// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_control_code_fast_state_type::TicketremoteControlCodeFastState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_control_code_fast_state`.
///
/// Obtain a handle from the [`TicketremoteControlCodeFastStateTableAccess::ticketremote_control_code_fast_state`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_control_code_fast_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_control_code_fast_state().on_insert(...)`.
pub struct TicketremoteControlCodeFastStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteControlCodeFastState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_control_code_fast_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteControlCodeFastStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteControlCodeFastStateTableHandle`], which mediates access to the table `ticketremote_control_code_fast_state`.
    fn ticketremote_control_code_fast_state(
        &self,
    ) -> TicketremoteControlCodeFastStateTableHandle<'_>;
}

impl TicketremoteControlCodeFastStateTableAccess for super::RemoteTables {
    fn ticketremote_control_code_fast_state(
        &self,
    ) -> TicketremoteControlCodeFastStateTableHandle<'_> {
        TicketremoteControlCodeFastStateTableHandle {
            imp: self.imp.get_table::<TicketremoteControlCodeFastState>(
                "ticketremote_control_code_fast_state",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteControlCodeFastStateInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteControlCodeFastStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteControlCodeFastStateTableHandle<'ctx> {
    type Row = TicketremoteControlCodeFastState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteControlCodeFastState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteControlCodeFastStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteControlCodeFastStateInsertCallbackId {
        TicketremoteControlCodeFastStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteControlCodeFastStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteControlCodeFastStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteControlCodeFastStateDeleteCallbackId {
        TicketremoteControlCodeFastStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteControlCodeFastStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteControlCodeFastStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteControlCodeFastStateTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteControlCodeFastStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteControlCodeFastStateUpdateCallbackId {
        TicketremoteControlCodeFastStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteControlCodeFastStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_control_code_fast_state`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteControlCodeFastStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_control_code_fast_state().id().find(...)`.
pub struct TicketremoteControlCodeFastStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteControlCodeFastState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteControlCodeFastStateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_control_code_fast_state`.
    pub fn id(&self) -> TicketremoteControlCodeFastStateIdUnique<'ctx> {
        TicketremoteControlCodeFastStateIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteControlCodeFastStateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteControlCodeFastState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TicketremoteControlCodeFastState>(
        "ticketremote_control_code_fast_state",
    );
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteControlCodeFastState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteControlCodeFastState>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteControlCodeFastState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_control_code_fast_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteControlCodeFastState`.
    fn ticketremote_control_code_fast_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteControlCodeFastState>;
}

impl ticketremote_control_code_fast_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_control_code_fast_state(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteControlCodeFastState> {
        __sdk::__query_builder::Table::new("ticketremote_control_code_fast_state")
    }
}
