// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberRequestTicketActionV3Args {
    pub version: u32,
    pub ticket_id: String,
    pub backend_id: String,
    pub action_id: String,
    pub target: String,
    pub source: String,
    pub reason: String,
    pub attempt_id: String,
    pub expected_interaction_revision: String,
    pub schedule_id: String,
}

impl From<TicketremoteMemberRequestTicketActionV3Args> for super::Reducer {
    fn from(args: TicketremoteMemberRequestTicketActionV3Args) -> Self {
        Self::TicketremoteMemberRequestTicketActionV3 {
            version: args.version,
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            action_id: args.action_id,
            target: args.target,
            source: args.source,
            reason: args.reason,
            attempt_id: args.attempt_id,
            expected_interaction_revision: args.expected_interaction_revision,
            schedule_id: args.schedule_id,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberRequestTicketActionV3Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_request_ticket_action_v3`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_request_ticket_action_v_3 {
    /// Request that the remote module invoke the reducer `ticketremote_member_request_ticket_action_v3` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_request_ticket_action_v_3:ticketremote_member_request_ticket_action_v_3_then`] to run a callback after the reducer completes.
    fn ticketremote_member_request_ticket_action_v_3(
        &self,
        version: u32,
        ticket_id: String,
        backend_id: String,
        action_id: String,
        target: String,
        source: String,
        reason: String,
        attempt_id: String,
        expected_interaction_revision: String,
        schedule_id: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_request_ticket_action_v_3_then(
            version,
            ticket_id,
            backend_id,
            action_id,
            target,
            source,
            reason,
            attempt_id,
            expected_interaction_revision,
            schedule_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_request_ticket_action_v3` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_request_ticket_action_v_3_then(
        &self,
        version: u32,
        ticket_id: String,
        backend_id: String,
        action_id: String,
        target: String,
        source: String,
        reason: String,
        attempt_id: String,
        expected_interaction_revision: String,
        schedule_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_request_ticket_action_v_3 for super::RemoteReducers {
    fn ticketremote_member_request_ticket_action_v_3_then(
        &self,
        version: u32,
        ticket_id: String,
        backend_id: String,
        action_id: String,
        target: String,
        source: String,
        reason: String,
        attempt_id: String,
        expected_interaction_revision: String,
        schedule_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberRequestTicketActionV3Args {
                version,
                ticket_id,
                backend_id,
                action_id,
                target,
                source,
                reason,
                attempt_id,
                expected_interaction_revision,
                schedule_id,
            },
            callback,
        )
    }
}
