// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteReleaseInvitationStreamArgs {
    pub ticket_id: String,
    pub invitation_id: String,
    pub session_id: String,
    pub sequence: u64,
}

impl From<TicketremoteReleaseInvitationStreamArgs> for super::Reducer {
    fn from(args: TicketremoteReleaseInvitationStreamArgs) -> Self {
        Self::TicketremoteReleaseInvitationStream {
            ticket_id: args.ticket_id,
            invitation_id: args.invitation_id,
            session_id: args.session_id,
            sequence: args.sequence,
        }
    }
}

impl __sdk::InModule for TicketremoteReleaseInvitationStreamArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_release_invitation_stream`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_release_invitation_stream {
    /// Request that the remote module invoke the reducer `ticketremote_release_invitation_stream` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_release_invitation_stream:ticketremote_release_invitation_stream_then`] to run a callback after the reducer completes.
    fn ticketremote_release_invitation_stream(
        &self,
        ticket_id: String,
        invitation_id: String,
        session_id: String,
        sequence: u64,
    ) -> __sdk::Result<()> {
        self.ticketremote_release_invitation_stream_then(
            ticket_id,
            invitation_id,
            session_id,
            sequence,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_release_invitation_stream` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_release_invitation_stream_then(
        &self,
        ticket_id: String,
        invitation_id: String,
        session_id: String,
        sequence: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_release_invitation_stream for super::RemoteReducers {
    fn ticketremote_release_invitation_stream_then(
        &self,
        ticket_id: String,
        invitation_id: String,
        session_id: String,
        sequence: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteReleaseInvitationStreamArgs {
                ticket_id,
                invitation_id,
                session_id,
                sequence,
            },
            callback,
        )
    }
}
