// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteCheckinGroup {
    pub id: String,
    pub direction: String,
    pub carriage: u8,
    pub status: String,
    pub count: u32,
    pub latest_at_ms: i64,
}

impl __sdk::InModule for TicketremoteCheckinGroup {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteCheckinGroup`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteCheckinGroupCols {
    pub id: __sdk::__query_builder::Col<TicketremoteCheckinGroup, String>,
    pub direction: __sdk::__query_builder::Col<TicketremoteCheckinGroup, String>,
    pub carriage: __sdk::__query_builder::Col<TicketremoteCheckinGroup, u8>,
    pub status: __sdk::__query_builder::Col<TicketremoteCheckinGroup, String>,
    pub count: __sdk::__query_builder::Col<TicketremoteCheckinGroup, u32>,
    pub latest_at_ms: __sdk::__query_builder::Col<TicketremoteCheckinGroup, i64>,
}

impl __sdk::__query_builder::HasCols for TicketremoteCheckinGroup {
    type Cols = TicketremoteCheckinGroupCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteCheckinGroupCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            direction: __sdk::__query_builder::Col::new(table_name, "direction"),
            carriage: __sdk::__query_builder::Col::new(table_name, "carriage"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
            latest_at_ms: __sdk::__query_builder::Col::new(table_name, "latest_at_ms"),
        }
    }
}
