// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteServiceBootstrapArgs {
    pub ticket_id: String,
    pub display_name: String,
    pub admin_email: String,
    pub phone_backend_id: String,
    pub phone_base_url: String,
    pub phone_attach_name: String,
    pub auth_issuer: String,
    pub auth_audience: String,
}

impl From<TicketremoteServiceBootstrapArgs> for super::Reducer {
    fn from(args: TicketremoteServiceBootstrapArgs) -> Self {
        Self::TicketremoteServiceBootstrap {
            ticket_id: args.ticket_id,
            display_name: args.display_name,
            admin_email: args.admin_email,
            phone_backend_id: args.phone_backend_id,
            phone_base_url: args.phone_base_url,
            phone_attach_name: args.phone_attach_name,
            auth_issuer: args.auth_issuer,
            auth_audience: args.auth_audience,
        }
    }
}

impl __sdk::InModule for TicketremoteServiceBootstrapArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_service_bootstrap`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_service_bootstrap {
    /// Request that the remote module invoke the reducer `ticketremote_service_bootstrap` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_service_bootstrap:ticketremote_service_bootstrap_then`] to run a callback after the reducer completes.
    fn ticketremote_service_bootstrap(
        &self,
        ticket_id: String,
        display_name: String,
        admin_email: String,
        phone_backend_id: String,
        phone_base_url: String,
        phone_attach_name: String,
        auth_issuer: String,
        auth_audience: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_service_bootstrap_then(
            ticket_id,
            display_name,
            admin_email,
            phone_backend_id,
            phone_base_url,
            phone_attach_name,
            auth_issuer,
            auth_audience,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_service_bootstrap` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_service_bootstrap_then(
        &self,
        ticket_id: String,
        display_name: String,
        admin_email: String,
        phone_backend_id: String,
        phone_base_url: String,
        phone_attach_name: String,
        auth_issuer: String,
        auth_audience: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_service_bootstrap for super::RemoteReducers {
    fn ticketremote_service_bootstrap_then(
        &self,
        ticket_id: String,
        display_name: String,
        admin_email: String,
        phone_backend_id: String,
        phone_base_url: String,
        phone_attach_name: String,
        auth_issuer: String,
        auth_audience: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteServiceBootstrapArgs {
                ticket_id,
                display_name,
                admin_email,
                phone_backend_id,
                phone_base_url,
                phone_attach_name,
                auth_issuer,
                auth_audience,
            },
            callback,
        )
    }
}
