// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteInvitationAction {
    pub id: String,
    pub ticket_id: String,
    pub invitation_id: String,
    pub command_id: String,
    pub kind: String,
    pub status: String,
    pub created_at: String,
    pub completed_at: String,
}

impl __sdk::InModule for TicketremoteInvitationAction {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteInvitationAction`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteInvitationActionCols {
    pub id: __sdk::__query_builder::Col<TicketremoteInvitationAction, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteInvitationAction, String>,
    pub invitation_id: __sdk::__query_builder::Col<TicketremoteInvitationAction, String>,
    pub command_id: __sdk::__query_builder::Col<TicketremoteInvitationAction, String>,
    pub kind: __sdk::__query_builder::Col<TicketremoteInvitationAction, String>,
    pub status: __sdk::__query_builder::Col<TicketremoteInvitationAction, String>,
    pub created_at: __sdk::__query_builder::Col<TicketremoteInvitationAction, String>,
    pub completed_at: __sdk::__query_builder::Col<TicketremoteInvitationAction, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteInvitationAction {
    type Cols = TicketremoteInvitationActionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteInvitationActionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            invitation_id: __sdk::__query_builder::Col::new(table_name, "invitation_id"),
            command_id: __sdk::__query_builder::Col::new(table_name, "command_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteInvitationAction`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteInvitationActionIxCols {
    pub id: __sdk::__query_builder::IxCol<TicketremoteInvitationAction, String>,
    pub invitation_id: __sdk::__query_builder::IxCol<TicketremoteInvitationAction, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteInvitationAction {
    type IxCols = TicketremoteInvitationActionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteInvitationActionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            invitation_id: __sdk::__query_builder::IxCol::new(table_name, "invitation_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteInvitationAction {}
