// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremotePushSubscription {
    pub id: String,
    pub ticket_id: String,
    pub email: String,
    pub endpoint: String,
    pub p_256_dh: String,
    pub auth: String,
}

impl __sdk::InModule for TicketremotePushSubscription {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremotePushSubscription`.
///
/// Provides typed access to columns for query building.
pub struct TicketremotePushSubscriptionCols {
    pub id: __sdk::__query_builder::Col<TicketremotePushSubscription, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremotePushSubscription, String>,
    pub email: __sdk::__query_builder::Col<TicketremotePushSubscription, String>,
    pub endpoint: __sdk::__query_builder::Col<TicketremotePushSubscription, String>,
    pub p_256_dh: __sdk::__query_builder::Col<TicketremotePushSubscription, String>,
    pub auth: __sdk::__query_builder::Col<TicketremotePushSubscription, String>,
}

impl __sdk::__query_builder::HasCols for TicketremotePushSubscription {
    type Cols = TicketremotePushSubscriptionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremotePushSubscriptionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            endpoint: __sdk::__query_builder::Col::new(table_name, "endpoint"),
            p_256_dh: __sdk::__query_builder::Col::new(table_name, "p_256_dh"),
            auth: __sdk::__query_builder::Col::new(table_name, "auth"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremotePushSubscription`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremotePushSubscriptionIxCols {
    pub id: __sdk::__query_builder::IxCol<TicketremotePushSubscription, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremotePushSubscription {
    type IxCols = TicketremotePushSubscriptionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremotePushSubscriptionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremotePushSubscription {}
