// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_checkin_self_type::TicketremoteCheckinSelf;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_member_checkin`.
///
/// Obtain a handle from the [`TicketremoteMemberCheckinTableAccess::ticketremote_member_checkin`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_member_checkin()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_member_checkin().on_insert(...)`.
pub struct TicketremoteMemberCheckinTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteCheckinSelf>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_member_checkin`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteMemberCheckinTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteMemberCheckinTableHandle`], which mediates access to the table `ticketremote_member_checkin`.
    fn ticketremote_member_checkin(&self) -> TicketremoteMemberCheckinTableHandle<'_>;
}

impl TicketremoteMemberCheckinTableAccess for super::RemoteTables {
    fn ticketremote_member_checkin(&self) -> TicketremoteMemberCheckinTableHandle<'_> {
        TicketremoteMemberCheckinTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteCheckinSelf>("ticketremote_member_checkin"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteMemberCheckinInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteMemberCheckinDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteMemberCheckinTableHandle<'ctx> {
    type Row = TicketremoteCheckinSelf;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteCheckinSelf> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteMemberCheckinInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberCheckinInsertCallbackId {
        TicketremoteMemberCheckinInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteMemberCheckinInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteMemberCheckinDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberCheckinDeleteCallbackId {
        TicketremoteMemberCheckinDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteMemberCheckinDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteMemberCheckinUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteMemberCheckinTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteMemberCheckinUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberCheckinUpdateCallbackId {
        TicketremoteMemberCheckinUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteMemberCheckinUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_member_checkin`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteMemberCheckinIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_member_checkin().id().find(...)`.
pub struct TicketremoteMemberCheckinIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteCheckinSelf, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteMemberCheckinTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_member_checkin`.
    pub fn id(&self) -> TicketremoteMemberCheckinIdUnique<'ctx> {
        TicketremoteMemberCheckinIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteMemberCheckinIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteCheckinSelf> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<TicketremoteCheckinSelf>("ticketremote_member_checkin");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteCheckinSelf>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TicketremoteCheckinSelf>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteCheckinSelf`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_member_checkinQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteCheckinSelf`.
    fn ticketremote_member_checkin(&self)
        -> __sdk::__query_builder::Table<TicketremoteCheckinSelf>;
}

impl ticketremote_member_checkinQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_member_checkin(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteCheckinSelf> {
        __sdk::__query_builder::Table::new("ticketremote_member_checkin")
    }
}
