// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_phone_current_report_type::TicketremotePhoneCurrentReport;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_phone_current_report`.
///
/// Obtain a handle from the [`TicketremotePhoneCurrentReportTableAccess::ticketremote_phone_current_report`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_phone_current_report()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_phone_current_report().on_insert(...)`.
pub struct TicketremotePhoneCurrentReportTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremotePhoneCurrentReport>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_phone_current_report`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremotePhoneCurrentReportTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremotePhoneCurrentReportTableHandle`], which mediates access to the table `ticketremote_phone_current_report`.
    fn ticketremote_phone_current_report(&self) -> TicketremotePhoneCurrentReportTableHandle<'_>;
}

impl TicketremotePhoneCurrentReportTableAccess for super::RemoteTables {
    fn ticketremote_phone_current_report(&self) -> TicketremotePhoneCurrentReportTableHandle<'_> {
        TicketremotePhoneCurrentReportTableHandle {
            imp: self
                .imp
                .get_table::<TicketremotePhoneCurrentReport>("ticketremote_phone_current_report"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremotePhoneCurrentReportInsertCallbackId(__sdk::CallbackId);
pub struct TicketremotePhoneCurrentReportDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremotePhoneCurrentReportTableHandle<'ctx> {
    type Row = TicketremotePhoneCurrentReport;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremotePhoneCurrentReport> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremotePhoneCurrentReportInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremotePhoneCurrentReportInsertCallbackId {
        TicketremotePhoneCurrentReportInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremotePhoneCurrentReportInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremotePhoneCurrentReportDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremotePhoneCurrentReportDeleteCallbackId {
        TicketremotePhoneCurrentReportDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremotePhoneCurrentReportDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremotePhoneCurrentReportUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremotePhoneCurrentReportTableHandle<'ctx> {
    type UpdateCallbackId = TicketremotePhoneCurrentReportUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremotePhoneCurrentReportUpdateCallbackId {
        TicketremotePhoneCurrentReportUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremotePhoneCurrentReportUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_phone_current_report`,
/// which allows point queries on the field of the same name
/// via the [`TicketremotePhoneCurrentReportIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_phone_current_report().id().find(...)`.
pub struct TicketremotePhoneCurrentReportIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremotePhoneCurrentReport, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremotePhoneCurrentReportTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_phone_current_report`.
    pub fn id(&self) -> TicketremotePhoneCurrentReportIdUnique<'ctx> {
        TicketremotePhoneCurrentReportIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremotePhoneCurrentReportIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremotePhoneCurrentReport> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremotePhoneCurrentReport>("ticketremote_phone_current_report");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremotePhoneCurrentReport>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremotePhoneCurrentReport>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremotePhoneCurrentReport`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_phone_current_reportQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremotePhoneCurrentReport`.
    fn ticketremote_phone_current_report(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremotePhoneCurrentReport>;
}

impl ticketremote_phone_current_reportQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_phone_current_report(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremotePhoneCurrentReport> {
        __sdk::__query_builder::Table::new("ticketremote_phone_current_report")
    }
}
