// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteTicketActionV3QueuedIntent {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub action_id: String,
    pub kind: String,
    pub target: String,
    pub source: String,
    pub reason: String,
    pub attempt_id: String,
    pub expected_interaction_revision: String,
    pub schedule_id: String,
    pub requested_email: String,
    pub private_payload_json: String,
    pub created_at: String,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteTicketActionV3QueuedIntent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteTicketActionV3QueuedIntent`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteTicketActionV3QueuedIntentCols {
    pub id: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub action_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub kind: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub target: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub source: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub reason: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub attempt_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub expected_interaction_revision:
        __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub schedule_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub requested_email:
        __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub private_payload_json:
        __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub created_at: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteTicketActionV3QueuedIntent, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteTicketActionV3QueuedIntent {
    type Cols = TicketremoteTicketActionV3QueuedIntentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteTicketActionV3QueuedIntentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            action_id: __sdk::__query_builder::Col::new(table_name, "action_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            target: __sdk::__query_builder::Col::new(table_name, "target"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            attempt_id: __sdk::__query_builder::Col::new(table_name, "attempt_id"),
            expected_interaction_revision: __sdk::__query_builder::Col::new(
                table_name,
                "expected_interaction_revision",
            ),
            schedule_id: __sdk::__query_builder::Col::new(table_name, "schedule_id"),
            requested_email: __sdk::__query_builder::Col::new(table_name, "requested_email"),
            private_payload_json: __sdk::__query_builder::Col::new(
                table_name,
                "private_payload_json",
            ),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteTicketActionV3QueuedIntent`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteTicketActionV3QueuedIntentIxCols {
    pub expires_at: __sdk::__query_builder::IxCol<TicketremoteTicketActionV3QueuedIntent, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteTicketActionV3QueuedIntent, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteTicketActionV3QueuedIntent {
    type IxCols = TicketremoteTicketActionV3QueuedIntentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteTicketActionV3QueuedIntentIxCols {
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteTicketActionV3QueuedIntent {}
