// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_ticket_interaction_type::TicketremoteTicketInteraction;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_ticket_interaction`.
///
/// Obtain a handle from the [`TicketremoteTicketInteractionTableAccess::ticketremote_ticket_interaction`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_ticket_interaction()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_ticket_interaction().on_insert(...)`.
pub struct TicketremoteTicketInteractionTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteTicketInteraction>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_ticket_interaction`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteTicketInteractionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteTicketInteractionTableHandle`], which mediates access to the table `ticketremote_ticket_interaction`.
    fn ticketremote_ticket_interaction(&self) -> TicketremoteTicketInteractionTableHandle<'_>;
}

impl TicketremoteTicketInteractionTableAccess for super::RemoteTables {
    fn ticketremote_ticket_interaction(&self) -> TicketremoteTicketInteractionTableHandle<'_> {
        TicketremoteTicketInteractionTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteTicketInteraction>("ticketremote_ticket_interaction"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteTicketInteractionInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteTicketInteractionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteTicketInteractionTableHandle<'ctx> {
    type Row = TicketremoteTicketInteraction;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteTicketInteraction> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteTicketInteractionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteTicketInteractionInsertCallbackId {
        TicketremoteTicketInteractionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteTicketInteractionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteTicketInteractionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteTicketInteractionDeleteCallbackId {
        TicketremoteTicketInteractionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteTicketInteractionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteTicketInteractionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteTicketInteractionTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteTicketInteractionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteTicketInteractionUpdateCallbackId {
        TicketremoteTicketInteractionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteTicketInteractionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_ticket_interaction`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteTicketInteractionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_ticket_interaction().id().find(...)`.
pub struct TicketremoteTicketInteractionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteTicketInteraction, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteTicketInteractionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_ticket_interaction`.
    pub fn id(&self) -> TicketremoteTicketInteractionIdUnique<'ctx> {
        TicketremoteTicketInteractionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteTicketInteractionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteTicketInteraction> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremoteTicketInteraction>("ticketremote_ticket_interaction");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteTicketInteraction>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteTicketInteraction>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteTicketInteraction`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_ticket_interactionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteTicketInteraction`.
    fn ticketremote_ticket_interaction(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteTicketInteraction>;
}

impl ticketremote_ticket_interactionQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_ticket_interaction(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteTicketInteraction> {
        __sdk::__query_builder::Table::new("ticketremote_ticket_interaction")
    }
}
