// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteFinalizeTicketActivationAttemptArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub attempt_id: String,
    pub outcome: String,
    pub reason: String,
}

impl From<TicketremoteFinalizeTicketActivationAttemptArgs> for super::Reducer {
    fn from(args: TicketremoteFinalizeTicketActivationAttemptArgs) -> Self {
        Self::TicketremoteFinalizeTicketActivationAttempt {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            attempt_id: args.attempt_id,
            outcome: args.outcome,
            reason: args.reason,
        }
    }
}

impl __sdk::InModule for TicketremoteFinalizeTicketActivationAttemptArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_finalize_ticket_activation_attempt`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_finalize_ticket_activation_attempt {
    /// Request that the remote module invoke the reducer `ticketremote_finalize_ticket_activation_attempt` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_finalize_ticket_activation_attempt:ticketremote_finalize_ticket_activation_attempt_then`] to run a callback after the reducer completes.
    fn ticketremote_finalize_ticket_activation_attempt(
        &self,
        ticket_id: String,
        backend_id: String,
        attempt_id: String,
        outcome: String,
        reason: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_finalize_ticket_activation_attempt_then(
            ticket_id,
            backend_id,
            attempt_id,
            outcome,
            reason,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_finalize_ticket_activation_attempt` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_finalize_ticket_activation_attempt_then(
        &self,
        ticket_id: String,
        backend_id: String,
        attempt_id: String,
        outcome: String,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_finalize_ticket_activation_attempt for super::RemoteReducers {
    fn ticketremote_finalize_ticket_activation_attempt_then(
        &self,
        ticket_id: String,
        backend_id: String,
        attempt_id: String,
        outcome: String,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteFinalizeTicketActivationAttemptArgs {
                ticket_id,
                backend_id,
                attempt_id,
                outcome,
                reason,
            },
            callback,
        )
    }
}
